### ISSUE TITLE
Bug: Warning: foreach() argument must be of type array|object, string given

### ISSUE THREAD

**Issue by webersonloureiro** [deliciousbrains/wp-amazon-s3-and-cloudfront#614] opened 2022-11-09 16:34 UTC
**Describe the bug**
Our company's Sentry is getting this message more than 3k monthly: `Warning: foreach() argument must be of type array|object, string given` at line 628 on /wp-content/plugins/amazon-s3-and-cloudfront/classes/as3cf-filter.php file. Here's the code the warning's happening:

`foreach ( $cache as &$cache_item ) {`

The $cache variable sometimes isn't returning an array.

**Suggestion**
The plugin already verifies if the $cache variable's empty. To solve this, it's important to improve this condition and check if the $cache variable is also an array. Here's an example:
```
if ( empty( $cache ) || ! is_array( $cache ) ) {
    $cache = array();
}
```

**Additional context**
WP Offload Media Lite - Version 3.0.2 
WordPress - Version 6.0.3

**Comment by eduardovillao** [comment] 2022-11-09 16:55
+1. The same error here!

**Comment by ianmjones** [comment] 2022-12-05 09:58
That's very strange.

1. Are you using an external cache?
2. What kind of values are you seeing in the `$cache` variable that aren't an array?

**Comment by ianmjones** [comment] 2022-12-19 09:35
Closing as unreproducible and no further information provided.

If anyone can answer my questions, feel free to comment as we'd love to know how non-array data is being returned, we can't see any path to create non-array data in the cache, and are unable to reproduce the problem.

**Closed by ianmjones** 2022-12-19 09:35 UTC
Labels: awaiting response, unconfirmed, bug
