### ISSUE TITLE
Fatal error: Cannot use object of type WP_Error as array

### ISSUE THREAD

**Issue by Endda** [deliciousbrains/wp-amazon-s3-and-cloudfront#271] opened 2015-08-27 23:14 UTC
I just applied the update to all three of my websites and it has broken all three of them. Images can not be uploaded to WordPress and offloaded to Amazon as it returns the following error. . .

"Fatal error: Cannot use object of type WP_Error as array in /homepages/31/d584948166/htdocs/testappstoreapps/wp-includes/media.php on line 196"

When the plugin is first updated, the media library is viewable, but as soon as you try to upload something, and get this error, then the media library cannot be viewed at all. The spinning dial just sits there and spins forever.

**Comment by Endda** [comment] 2015-08-27 23:14
I have even tried to downgrade to a backup version(the one just before this new one) and while it does allow images to be uploaded, the media library is still not viewable

**Comment by Endda** [comment] 2015-08-28 00:49
Restoring from a complete backup(website and database) from 2 days ago resolves the error as long as I don't update the plugin

**Comment by A5hleyRich** [comment] 2015-08-28 07:12
Please can you provide your diagnostic information found from within the support tab?

**Comment by phpbits** [comment] 2015-08-28 10:02
Any fix?? I'm having the same error! 

Thanks!

**Comment by A5hleyRich** [comment] 2015-08-28 10:27
@phpbits I'm currently not able to replicate this issue. Can you send me your diagnostic information from the support tab?

**Comment by Endda** [comment] 2015-08-28 13:01
site_url(): http://www.appstoreapps.com
home_url(): http://www.appstoreapps.com
Database Name: db587137082
Table Prefix: wp_
WordPress: 4.3
Web Server: Apache
PHP: 5.5.28
MySQL: 5.5.44-0+deb7u1
ext/mysqli: yes
WP Memory Limit: 64M
Blocked External HTTP Requests: None
WP Locale: en_US
Debug Mode: No
WP Max Upload Size: 8 MB
PHP Time Limit: 50000
PHP Error Log: 
fsockopen: Enabled
OpenSSL: OpenSSL 0.9.8o 01 Jun 2010
cURL: Enabled
Zlib Compression: Enabled

Media Files: 13,721
Media Files on S3: 11,190
Number of Image Sizes: 15

Bucket: appstoreapps.com
Region: 
Copy Files to S3: On
Rewrite File URLs: On

URL Preview: http://appstoreapps.com.s3.amazonaws.com/wp‑content/uploads/20150828085814/photo.jpg

Domain: subdomain
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: Off
SSL: request
Remove Files From Server: On
Object Versioning: On
Far Future Expiration Header: Off
Copy HiDPI (@2x) Images: Off

Active Plugins:
WP Offload S3 (v0.9.4) by Delicious Brains
Amazon Web Services (v0.3.2) by Delicious Brains
Applay - Shortcodes (v2.2) by Leafcolor
Contact Form 7 (v4.2.2) by Takayuki Miyoshi
Easy Plugin for AdSense (v8.60) by 
EWWW Image Optimizer (v2.5.0) by Shane Bishop
WPBakery Visual Composer (v4.6.2) by Michael M - WPBakery.com
OIO Ad Manager (v2.60) by Simon Emery
Shortcoder (v3.4) by Aakash Chakravarthy
UK Cookie Consent (v1.8.2) by Catapult
W3 Total Cache (v0.9.4.1) by Frederick Townes
WooCommerce Improved External Products (v1.2.2) by Jeremiah Prummer
WooCommerce (v2.4.6) by WooThemes
Yoast SEO (v2.3.4) by Team Yoast
WP-PageNavi (v2.88) by Lester 'GaMerZ' Chan

_________________


This is happening on a site where even Woocommerce/applay stuff isn't installed on. Here is the diagnostic information from that one



site_url(): http://www.androidexplained.com
home_url(): http://www.androidexplained.com
Database Name: db584988612
Table Prefix: wp_
WordPress: 4.3
Web Server: Apache
PHP: 5.5.28
MySQL: 5.1.73-1+deb6u1
ext/mysqli: yes
WP Memory Limit: 40M
Blocked External HTTP Requests: None
WP Locale: en_US
Debug Mode: No
WP Max Upload Size: 8 MB
PHP Time Limit: 600
PHP Error Log: 
fsockopen: Enabled
OpenSSL: OpenSSL 0.9.8o 01 Jun 2010
cURL: Enabled
Zlib Compression: Enabled

Media Files: 1,619
Media Files on S3: 55
Number of Image Sizes: 9

Bucket: androidexplained.com
Region: us-west-2
Copy Files to S3: On
Rewrite File URLs: On

URL Preview: http://androidexplained.com.s3‑us‑west‑2.amazonaws.com/wp‑content/uploads/2015/08/28090022/photo.jpg

Domain: subdomain
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
SSL: request
Remove Files From Server: On
Object Versioning: On
Far Future Expiration Header: Off
Copy HiDPI (@2x) Images: Off

Active Plugins:
WP Offload S3 (v0.9.4) by Delicious Brains
Amazon Web Services (v0.3.2) by Delicious Brains
Disqus Comment System (v2.84) by Disqus 
Easy Plugin for AdSense (v8.60) by 
EWWW Image Optimizer (v2.5.0) by Shane Bishop
Explanatory Dictionary (v4.1.5) by EXED internet (RJvD, BHdH)
FooBox Free Image Lightbox (v1.0.7) by FooPlugins
FooGallery (v1.2.4) by FooPlugins
MailChimp for WordPress Lite (v2.3.8) by ibericode
OIO Ad Manager (v2.60) by Simon Emery
Recent Posts Widget Extended (v0.9.9.2) by Satrya
Shortcoder (v3.4) by Aakash Chakravarthy
Social Media Feather (v1.7.8) by Synved
UK Cookie Consent (v1.8.2) by Catapult
W3 Total Cache (v0.9.4.1) by Frederick Townes
Yoast SEO (v2.3.4) by Team Yoast
WP-Appbox (v3.2.2) by Marcel Schmilgeit
WP-PageNavi (v2.88) by Lester 'GaMerZ' Chan
WP-Polls (v2.70) by Lester 'GaMerZ' Chan
WP Post Navigation (v1.2.3) by Anas Mir
Clef (v2.3.0) by Clef
Yet Another Related Posts Plugin (v4.2.4) by Adknowledge

______________________

It's happening to other people as they are starting to reply to my WordPress Plugin Support forum thread too. This a widespread issue in my view

**Comment by davidhealey** [comment] 2015-08-28 19:33
I'm experiencing a similar problem with the latest version. I can upload media files just fine but when I go to the media library in WP the little dial just keeps going around but it never displays the media items. If I filter by image then it will display images but with the audio filter (the only other media type I have on my site) doesn't display anything.

**Comment by JackSW** [comment] 2015-08-28 19:37
I am also having this issue. I can see that the metadata is messed up for all images that have been uploaded using the latest plugin version. Example row from database
 26130 |   13460 | _wp_attachment_metadata | O:8:"WP_Error":2:{s:6:"errors";a:1:{s:9:"exception";a:1:{i:0;s:93:"File /srv/www/bbwordpress/current/wp-content/uploads/2015/08/orange-781119.png does not exist";}}s:10:"error_data";a:0:{}}

**Comment by Endda** [comment] 2015-08-30 02:23
Okay, as a workaround to this error, I had to revert back to the old version of the 'amazon-s3-and-cloudfront' plugin. Then, I had to dive into phpmyadmin, head into the postmeta table and sort by post id. Making it so that it showed all of the newer entries in this table. Then I looked at all entries for the error that has been talked about here(the wp_error).

Any post id entry that shared the same number as one with the wp error issue, I deleted. Then I went into the wordpress wp-admin section, looked at the library and it showed up, but with some images that couldn't be displayed. I then clicked on each one and deleted it so that it was completely removed

Once all this was done, I am now able to upload images and the plugin(with the last version, not the new version) will send, host and display these images from my Amazon AWS bucket, and now I can see all of my stuff from the library

This isn't a fix, just a workaround that I discovered by fiddling around and trying different things out. Hopefully the developers will be able to find the root cause of the issue and fix it in a future update(positive thoughts)

**Comment by hickham** [comment] 2015-08-30 03:04
Same problem here!
Fatal error: Cannot use object of type WP_Error as array in /var/www/arquidicas.com.br/htdocs/wp-includes/media.php on line 196 =/

Any solution?

**Comment by polevaultweb** [comment] 2015-08-30 08:29
We are working on a fix for this and will release shortly. So we can cover all bases, @hickham @JackSW  @davidhealey @phpbits could you post your diagnostic info please?

**Comment by davidhealey** [comment] 2015-08-30 12:05
### WordPress Environment ###

Home URL: http://xtant-audio.com
Site URL: http://xtant-audio.com/wordpress
WC Version: 2.4.6
Log Directory Writable: ✔  /var/www/vhosts/xtant-audio.com/httpdocs/wordpress/wp-content/uploads/wc-logs/
WP Version: 4.3
WP Multisite: –
WP Memory Limit: 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.40
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.41
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.4.6
: 
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (33) ###

Aelia Blacklister for WooCommerce: by Aelia (Diego Zanella) – 0.8.5.150112-beta
WP Affiliate Manager: by wp.insider
wpaffiliatemgr – 2.1.5

WP Offload S3 Tweaks: by Delicious Brains – 0.1.1
WP Offload S3: by Delicious Brains – 0.9.4
Amazon Web Services: by Delicious Brains – 0.3.2
Awesome Support WooCommerce: by Awesome Support Team – 1.0.2
Awesome Support: by ThemeAvenue – 3.1.12
BackWPup: by Inpsyde GmbH – 3.1.4
Contact Form 7: by Takayuki Miyoshi – 4.2.2
Enhanced Media Library: by wpUXsolutions – 2.0.4.7
Google Analytics Dashboard for WP: by Alin Marcu – 4.8.2
Homepage Control: by WooThemes – 2.0.1
HTML5 Responsive FAQ: by Aman Verma – 2.4
MailChimp for WordPress Lite: by ibericode – 2.3.8
Meta Slider: by Matcha Labs – 3.3.4.1
Organized Docs: by Isabel Castillo – 2.2
Social Media Widget: by Noah Kagan – 4.0.4
Storefront Product Sharing: by WooThemes – 1.0.2
Storefront Site Logo: by WooAssist – 1.1.2
Storefront WooCommerce Customiser: by WooThemes – 1.6.0
Aelia Foundation Classes for WooCommerce: by Aelia – 1.6.6.150825
WooCommerce Amazon S3 Storage: by WooThemes – 2.1.0
WooCommerce EU VAT Assistant: by Aelia (Diego Zanella) – 1.4.11.150810
WooCommerce PayPal Adaptive Payments: by WooThemes – 1.1.4
WooCommerce MailChimp: by Adam Anderly – 1.3.6
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.22
WooCommerce Product Bundles: by WooThemes – 4.11.3
Woocommerce Product Tabs: by Nilambar Sharma – 1.1
WooCommerce: by WooThemes – 2.4.6
WooThemes Helper: by WooThemes – 1.5.9
WordPress Importer: by wordpressdotorg – 0.6.1
WP Maintenance Mode: by Designmodo – 2.0.3
WP Super Cache: by Automattic – 1.4.4

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.0.0

### WC Pages ###

Shop Base: #22 - /products/
Basket: #23 - /basket/
Checkout: #24 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront Child Theme
Version: 1.0 – 1.5.0 is available
Author URL: http://woothemes.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 1.5.0
Parent Theme Author URL: http://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/emails/email-footer.php
storefront-child/woocommerce/myaccount/form-login.php

**Comment by modalia** [comment] 2015-08-30 19:00
Hello, since I've updated the plugin have a similar problem:

Fatal error: Cannot use object of type WP_Error as array in /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-s3-and-cloudfront.php on line 1171

![de compras el comparador de moda de modalia es](https://cloud.githubusercontent.com/assets/14043881/9568925/90688664-4f59-11e5-9d34-97f0bd55ab43.png)
![productos compras modalia es wordpress](https://cloud.githubusercontent.com/assets/14043881/9568926/90692cae-4f59-11e5-9f61-9525ab5a74c5.png)

Here are some data on the server, database and template.

Congratulations on your plugin . Thank you!!!

compras.modalia.es

Server Environment
Información del Servidor:	[?]	Apache/2.4.7 (Ubuntu)
Versión de PHP:	[?]	5.5.9-1ubuntu4.11
PHP Publicar Tamaño máximo:	[?]	128 MB
Límite de Tiempo PHP:	[?]	-1
Vars entrada PHP Max:	[?]	1000
SUHOSIN Instalado:	[?]	–
Versión de MySQL:	[?]	5.6.23
Tamaño máximo de subida:	[?]	128 MB
Por defecto la zona horaria es GMT:	[?]	✔
fsockopen/cURL:	[?]	 ✔
SoapClient:	[?]	 ✔
DOMDocument:	[?]	 ✔
GZip:	[?]	 ✔
Publicar remoto:	[?]	 ✔
Obtén remoto:	[?]	 ✔

WC Database Versión:	[?]	2.4.6
woocommerce_api_keys	 	✔
woocommerce_attribute_taxonomies	 	✔
woocommerce_termmeta	 	✔
woocommerce_downloadable_product_permissions	 	✔
woocommerce_order_items	 	✔
woocommerce_order_itemmeta	 	✔
woocommerce_tax_rates	 	✔
woocommerce_tax_rate_locations	 	✔


Plugins activos (18)
404page	 	por smartware.cc – 1.4
LayerSlider WP	 	por Kreatura Media – 5.5.0
WP Offload S3	 	por Delicious Brains – 0.9.4
Amazon Web Services	 	por Delicious Brains – 0.3.2
Duplicator	 	por LifeInTheGrid – 0.5.28
FEEDZY RSS Feeds by b*web	 	por Brice CAPOBIANCO – 2.6
Fusion Core	 	por ThemeFusion – 1.7.5
Hello Dolly	 	por Matt Mullenweg – 1.6
Revolution Slider	 	por ThemePunch – 4.6.93
W3 Total Cache	 	por Frederick Townes – 0.9.4.1
WooCommerce Product Search	 	por itthinx – 1.4.1
WooCommerce	 	por WooThemes – 2.4.6
WooThemes Helper	 	por WooThemes – 1.5.9
Yoast SEO	 	por Equipo Yoast – 2.3.4
WP All Import Pro	 	por Soflyy – 4.1.7
WP All Import - WooCommerce Add-On Pro	 	por Soflyy – 2.1.7
XCloner	 	por Liuta Ovidiu – 3.1.3
YITH WooCommerce Zoom Magnifier	 	por Yithemes – 1.2.7

Tema
Nombre:	[?]	Avada Child
Versión:	[?]	1.0.0
Autor URL:	[?]	https://theme-fusion.com
Tema Hijo:	[?]	✔
Padres Nombre Tema:	[?]	Avada
Tema Padres Versión:	[?]	3.8.6
Tema Padres Autor URL:	[?]	http://themeforest.net/user/ThemeFusion
Soporte WooCommerce:	[?]	✔

**Comment by phpbits** [comment] 2015-08-31 11:53
Hi,

Any fix available yet?

**Comment by polevaultweb** [comment] 2015-09-01 09:03
The fix for this has just been released as 0.9.5, let us know how that goes and thanks for your patience.

**Comment by modalia** [comment] 2015-09-01 16:00
Hello, I updated the plugin and fixed the error: WP_Error array as in .... wp-includes / media.php on line 196.

But now, some products give me this error: Fatal error: Can not use object of type WP_Error as array in / var / www / html / wp-content / plugins / amazon-s3-and-CloudFront / classes / amazon-s3-and -cloudfront.php on line 1159

I have commented the lines 1159-1165.

These are:

// We only need to encode said resized image files Error Can not use object of type array as WP_Error
/ * If (! Isset ($ data ['sizes'])) {
return $ data;
}

foreach ($ data ['sizes'] as $ key => $ size) {
$ data ['sizes'] [$ key] ['file'] = $ this-> encode_filename_in_path ($ data ['sizes'] [$ key] ['file']);
} * /

So far, I've managed to fix the error.

Any suggestions?

Thank you for your great plugin

**Comment by tallgirltexas** [comment] 2015-09-01 23:54
I am having the same issues with the media library and have submitted a help ticket through the plugin page on my website. 

I was sent a notification that there was an update, which I did apply and now I can upload images through the media uploader, but I still cannot see images in thumbnail view and the only images I can see are the ones I just uploaded. (see image 1)
![1](https://cloud.githubusercontent.com/assets/14082978/9619938/be797bc6-50da-11e5-8005-9b4cb3ad3f34.png)

In the Settings section, I see a nag that says 5% of images are not uploaded (see image 2) 
![2](https://cloud.githubusercontent.com/assets/14082978/9619943/c84b1a42-50da-11e5-8349-8f17ec9fd6e5.png)

And when I click on it I get a new error message (see image 3)
 
![3](https://cloud.githubusercontent.com/assets/14082978/9619945/cbc8cd54-50da-11e5-8045-52803a1b2529.png)

My latest diagnostics are here:
site_url(): http://www.simplyamusingdesigns.com
home_url(): http://www.simplyamusingdesigns.com
Database Name: tallg1rl_simplyamusingdesign
Table Prefix: wp_abg6ji_
WordPress: 4.3
Web Server: Apache
PHP: 5.4.43
MySQL: 5.5.42-37.1
ext/mysqli: no
WP Memory Limit: 40M
Blocked External HTTP Requests: None
WP Locale: en_US
Debug Mode: No
WP Max Upload Size: 64 MB
PHP Time Limit: 30
PHP Error Log: error_log
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1e-fips 11 Feb 2013
cURL: Enabled
Zlib Compression: Enabled

Media Files: 426
Media Files on S3: 406
Number of Image Sizes: 7

Bucket: simplyamusingdesigns
Region: us-west-2
Copy Files to S3: On
Rewrite File URLs: On

URL Preview: http://simplyamusingdesigns.s3‑us‑west‑2.amazonaws.com/wp‑content/uploads/2015/09/01173313/photo.jpg

Domain: subdomain
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
SSL: request
Remove Files From Server: Off
Object Versioning: On
Far Future Expiration Header: On
Copy HiDPI (@2x) Images: Off

Active Plugins:
Gravity Forms (v1.9.13) by rocketgenius
Akismet (v3.1.3) by Automattic
WP Offload S3 - Pro Upgrade (v1.0.1) by Delicious Brains
WP Offload S3 (v0.9.5) by Delicious Brains
Amazon Web Services (v0.3.2) by Delicious Brains
Genesis eNews Extended (v2.0.1) by Brandon Kraft
Genesis Featured Widget Amplified (v0.8.1) by Nick_theGeek
Genesis Responsive Slider (v0.9.3) by StudioPress
Lightbox Gallery (v0.8.2) by Hiroaki Miyashita
MailChimp for WordPress Lite (v2.3.9) by ibericode
Popup with fancybox (v2.0) by Gopi Ramasamy
Portfolio Post Type (v0.9.1) by Devin Price
Redirection (v2.3.16) by John Godley
Simple Social Icons (v1.0.9) by Nathan Rice
Testimonials Wordpress plugin (v1.2) by husamrayan
Yoast SEO (v2.3.4) by Team Yoast
WP Rocket (v2.6.7) by WP Rocket


Many thanks!

**Comment by polevaultweb** [comment] 2015-09-24 11:28
Fixed in 0.9.5

**Closed by polevaultweb** 2015-09-24 11:28 UTC
