### ISSUE TITLE
Error fetching buckets — [curl] 77: [url] https://s3.amazonaws.com/

### ISSUE THREAD

**Issue by prashantimpinge** [deliciousbrains/wp-amazon-s3-and-cloudfront#296] opened 2015-11-26 18:25 UTC
Hello,

I have facing this issue on AWS ElasticBeanstalk. Please help me to resolve this issue. This is urgent.

Thanks!
Prashant

**Comment by polevaultweb** [comment] 2015-11-26 18:26
@prashantimpinge https://wordpress.org/support/topic/error-fetching-buckets-curl-77-url-httpss3amazonawscom-1?replies=2#post-7711820

**Comment by prashantimpinge** [comment] 2015-11-26 18:59
Hi Iain, Thanks for your reply. I have tried to restart my app. But still not working. It give same error message. My AWS Server configuration is:

64bit Amazon Linux 2015.09 v2.0.4 running PHP 5.6

DIAGNOSTIC INFO FOR THE PLUGIN

WordPress: 4.3.1
Web Server: Apache
PHP: 5.6.14
MySQL: 5.6.19-log
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Blocked External HTTP Requests: None
WP Locale: en_US
Debug Mode: No
WP Max Upload Size: 2 MB
PHP Time Limit: 60
PHP Error Log:
WP Cron: Enabled
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1k-fips 8 Jan 2015
cURL: Enabled
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled

**Comment by prashantimpinge** [comment] 2015-11-26 19:22
Iain, Please help me for resolving this issue. Thanks!

**Comment by A5hleyRich** [comment] 2015-11-27 08:17
Does running `curl -I https://s3.amazonaws.com/` from the server yield the same result?

**Comment by aaemnnosttv** [comment] 2017-06-27 15:51
Closing as we are unable to reproduce the problem. Please re-open if this is still an issue.

**Closed by aaemnnosttv** 2017-06-27 15:51 UTC
