### ISSUE TITLE
S3 image replacement failing in theme Header when domain is mapped

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#383] opened 2017-06-27 16:28 UTC
- Multisite environment
- WooCommerce Storefront theme
- Wordpress 2017 Theme
- Divi theme
- Domain Mapping on **SUBBLOG** Repeat...subblog with domain mapping

**Problem:** 
Mapped Domain Breaking the S3 Image Replacement for Header Image when viewing via Mapped Domain (works fine when viewing non mapped domain), and other various background images. Inserted into post images, woocommerce images seem to work fine in limited testing.

The S3 image shows up fine in all scenarious when domain mapping is not used (ie: networkdomain.com/subblog)

HOWEVER, when mapping a domain www.mappeddomain.com to networkdomain.com/subblog, the header image path is displaying the local image path instead of the mapped image path.

**Method:**
Adding an image in the header with the customizer, or using a background image in section on divi

Again, the other S3 images for products are showing the s3 image paths with no issue when domain is mapped and s3 image pathes are working fine when placed in addition css section when visiting via mapped domain method or original path method

**Comment by aaemnnosttv** [comment] 2017-06-27 20:33
Are you able to reproduce the issue using a core WordPress theme such as Twenty Seventeen?

If so, please provide us the diagnostic information from the Support tab of your install so we can take a closer look.

**Comment by mrbm** [comment] 2017-06-27 21:53
Doesn't work on 2017 either...

**Comment by mrbm** [comment] 2017-06-27 22:03
site_url(): https://mydomain.com
home_url(): http://mydomain.com
Database Name: switch_wordpress
Table Prefix: wp_
WordPress: 4.8 Multisite (subdirectory)
Multisite Site Count: 62
Domain Mapping: Enabled
Web Server: Apache
PHP: 7.0.19-1+deb.sury.org~trusty+1
MySQL: 5.5.55
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 64M
Memory Usage: 14 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 5 MB
PHP Time Limit: 300
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.2k  26 Jan 2017
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.2.3
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 8,035
Media Files on S3: 8,013
Number of Image Sizes: 10

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
post-thumbnail (none)
slider-post-thumbnail (1140x440)
image_post_format (750x440)
related-thumb (160x160)
portfolio-large-th (550x210)
portfolio-small-th (265x100)

WP_CONTENT_DIR: /home/wordpress/public_html/wp-content
WP_CONTENT_URL: http://mydomain.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /home/wordpress/public_html/wp-content/plugins
WP_PLUGIN_URL: http://mydomain.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: mybucket
Region: us-west-1
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
http://mydomain.com/wp‑content/uploads/2017/06/photo.jpg
S3 URL:
https://mybucket.s3.amazonaws.com/content/uploads/2017/06/27215945/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: content/uploads/
Use Year/Month: On
Force HTTPS: Off
Remove Files From Server: On
Object Versioning: On

Active Theme Name: Top Fixed Nav
Active Theme Folder: sitefixednav
Parent Theme Folder: duena

Active Plugins:
Admin Footer Text (v1.0.9) by S H Mohanjith (Incsub), Andrew Billits (Incsub)
Admin Help Content (v2.0.1) by Andrew Billits, Ulrich Sossou (Incsub), Ve Bailovity (Incsub)
Affiliate (v3.1.6.7) by WPMU DEV
Amazon Web Services (v1.0.3) by Delicious Brains
Coming Soon Page & Maintenance Mode by SeedProd (v5.0.5) by SeedProd
Contact Form 7 (v4.8) by Takayuki Miyoshi
Custom Content Dashboard Widget (v1.6.3.1) by S H Mohanjith (Incsub), Andrew Billits (Incsub)
Domain Mapping (v4.4.2.5) by WPMU DEV
Easy Blogging (v3.3.5) by WPMU DEV
Easy Google Fonts (v1.4.3) by Titanium Themes
FitVids for WordPress (v3.0.3) by 
Footer Content (v1.0.2.5) by S H Mohanjith (Incsub), Andrew Billits (Incsub)
GearFoundation Quotas (vv 1.0) by Ben M
GearFoundation Stripe Connect (vv 1.0) by Ben M
GearFoundation Upfront Fancy Gallery Compatibility and Customize Menu fixes (vv 1.0) by Ben M
MailChimp Sync (v1.9.3) by WPMU DEV
Multisite Theme Manager (v1.1.4) by WPMU DEV
New Blog Templates (v2.8.5) by WPMU DEV
Pro Sites (v3.5.5) by WPMU DEV
Really Simple CAPTCHA (v2.0) by Takayuki Miyoshi
Regenerate Thumbnails (v2.2.6) by Alex Mills (Viper007Bond)
Remove Email Verification (v2.4.1) by WPMU DEV
Set Password on Multisite Blog Creation (v1.1.2.3) by WPMU DEV
Signup TOS (v1.4) by WPMU DEV
Simple Custom CSS (v3.3) by John Regan, Danny Van Kooten
Snapshot Pro (v3.1.2) by WPMU DEV
Soliloquy (v2.3.9.6) by Thomas Griffin
Support System (v2.1.9.3) by WPMU DEV
Toggle wpautop (v1.2.5) by Linchpin
Ultimate Branding (v1.8.7) by WPMU DEV
Video Thumbnails (v2.12.3) by Sutherland Boswell
WP Defender Pro (v1.6.1) by WPMU DEV
WP Offload S3 Lite (v1.2) by Delicious Brains
WP-PageNavi (v2.91) by Lester 'GaMerZ' Chan
WPMU DEV Dashboard (v4.3.1) by WPMU DEV
WooThemes Helper (v1.6.2) by WooThemes

Must-use Plugins:
admin-title-mod.phpcrossdomain-cart-help.phpupfront-logo-fix.phpwidget-dash.phpwoocommerce-wizard-mod.phpwpmail.php

Drop-ins:
blog-suspended.php - Anti-Splog (Feature: Spammed Notice and Splog Review Form)
sunrise.php - sunrise.php

**Comment by aaemnnosttv** [comment] 2017-06-28 08:05
We've had similar reports before but it has been difficult to reproduce. We'll look into this some more and follow up when we know more.

**Comment by mrbm** [comment] 2017-06-30 17:10
Do you want me to set up a test server for you....?

Noticing also if i try to do a workaround and place the full s3 image path
in the css...the image in the domain mapped mode gets rewritten to a local
path...

This is on the latest version of wordpress, using wpmudev domain mapping
plugin, and subblog multisite set up with apache.

Pretty standard install, does this match what you are testing against?

**Comment by mrbm** [comment] 2017-07-04 19:31
starting to see how to find this bug...and I believe this bug needs to get up on the priority list..

When domain mapping is enabled in a multisite environment, the subblogs that have a mapped domain arent having their image pathes adusted with the s3 paths. 

For instance, in the 2017 wordpress theme, using a header image background that is over 1600 pixels wide looks fine, but upon further inspection...its not when domain mapping is enabled.

viewing the page: https://networkname.com/subblog/ and then inspecting the header image reveals:
```

<div id="wp-custom-header" class="wp-custom-header">
<img src="https://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor.jpg" width="1600" height="900" alt="Bathroom Cobra" srcset="https://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor.jpg 1600w, https://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor-300x169.jpg 300w, https://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor-768x432.jpg 768w, https://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor-1024x576.jpg 1024w, https://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor-1080x608.jpg 1080w" sizes="100vw">
</div>
```
Now when I activate domain mapping, and view the page: http://mappeddomainofsubblog.com the same code block shows a slightly different image path:
```
<div id="wp-custom-header" class="wp-custom-header">
<img src="http://networkname.com/subblog/wp-content/uploads/sites/74/2017/07/bathroombackground-compressor.jpg" width="1600" height="900" alt="Bathroom Cobra" srcset="http://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor.jpg 1600w, http://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor-300x169.jpg 300w, http://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor-768x432.jpg 768w, http://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor-1024x576.jpg 1024w, http://xxx.s3.amazonaws.com/content/uploads/sites/74/2017/07/04181718/bathroombackground-compressor-1080x608.jpg 1080w" sizes="100vw">
</div>
```

This issue isn't so bad in 2017 wordpress theme because of the responsive image paths being correct are overriding the bad image path.

However I am noticing this issue also happen when using domain mapping in Divi for background images. Normal inserted images appear without issue.

So...looks like something was overlooked, are you able to see the issue now?

Using WPMUDEV domain mapping plugin

**Comment by mrbm** [comment] 2017-07-04 19:53
remember when testing....you need to test with wordpress multi-site set up and domain mapping plugin to reproduce the error...otherwise the error will not show.

**Comment by mrbm** [comment] 2017-07-05 21:39
to add to this...am peaking around the code...cold be way off..:

function get_urls_from_content

is used in the function find_urls_and_replace

which is used in the part of the function process_content (line 238 file classes/as3cf-filter.php ), which uses find_urls_and_replace to  "Find leftover URLs", while get_urls_from_img_src is used for the img src replacement strategy.

Img src replacement working great...but the other stuff isn't for mapped domains.

I think this function relies on a base url for matching stuff....so if a domain is mapped and its looking for the networkname/subblog...not sure if it will be working. Perhaps this is the oversite and the function isn't working.

I barely know the codebase...so could be wayyy off. But this issue is very repeatable for me...and a pretty big one. Love to know what you guys are seeing on this and i can set up a test server for you to use. Its my last roadblock from launch, so hope hear from you soon!

**Comment by nazarioa** [comment] 2017-08-04 02:54
We are seeing the same issue but we are not using a multiset setup. We are however hosting on WPEngine and I am not sure what odd stuff they may be doing.

Is there some specific information that could be helpful to you guys that I can provide?

**Comment by aaemnnosttv** [comment] 2017-08-04 08:55
@nazarioa if you could include your diagnostic information from the Support tab for us to see, that should include everything we need.

**Comment by nazarioa** [comment] 2017-08-04 20:04
bellow is the information you request. I did replace our URL with ANON

~~~~
site_url(): https://www.ANON.com
home_url(): http://www.ANON.com
Database Name: wp_ANON
Table Prefix: wp_
WordPress: 4.8
Web Server: Apache
PHP: 5.6.30-1+wpengine8
MySQL: 5.6.36
ext/mysqli: yes
PHP Memory Limit: 512M
WP Memory Limit: 40M
Memory Usage: 72 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 50 MB
PHP Time Limit: 3600
PHP Error Log: /var/log/apache2/ANON.error.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.1.1-dev
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 1,202
Media Files on S3: 1,136
Number of Image Sizes: 16

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
portfolio-square (570x570)
portfolio-portrait (600x800)
portfolio-landscape (800x600)
menu-featured-post (345x198)
qode-carousel_slider (400x260)
portfolio_slider (500x380)
portfolio_masonry_regular (500x500)
portfolio_masonry_wide (1000x500)
portfolio_masonry_tall (500x1000)
portfolio_masonry_large (1000x1000)
portfolio_masonry_with_space (700x0)
latest_post_boxes (539x303)

WP_CONTENT_DIR: /nas/content/live/ANON/wp-content
WP_CONTENT_URL: http://www.ANON.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /nas/content/live/ANON/wp-content/plugins
WP_PLUGIN_URL: http://www.ANON.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: ANON.com
Region: 
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
http://www.ANON.com/wp‑content/uploads/2017/08/photo.jpg
S3 URL:
https://dgllg7gnr5c6q.cloudfront.net/uploads/2017/08/04130054/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: uploads/
Use Year/Month: On
Force HTTPS: Off
Remove Files From Server: On
Object Versioning: On

Active Theme Name: Index Bridge Child
Active Theme Folder: ANON-bridge-child
Parent Theme Folder: bridge

Active Plugins:
Amazon Web Services (v1.0.3) by Delicious Brains
Antispam Bee (v2.7.1) by pluginkollektiv
Compress JPEG & PNG images (v2.2.4) by TinyPNG
Contact Form 7 (v4.8.1) by Takayuki Miyoshi
Duplicate Post (v3.2) by Enrico Battocchi
Easy Google Fonts (v1.4.3) by Titanium Themes
Enable Media Replace (v3.1.1) by Måns Jonasson
Envato WordPress Toolkit (v1.7.3) by Envato
Greenhouse Job Board (v2.7.2) by Brown Bag Marketing
HTML Page Sitemap (v1.3) by 
HubSpot Tracking Code for WordPress (v1.2.1) by HubSpot
LayerSlider WP (v5.6.5) by Kreatura Media
Qode Instagram Widget (v1.0) by Qode Themes
Redirection (v2.6.6) by John Godley
Simple Custom CSS (v3.3) by John Regan, Danny Van Kooten
Spacer (v3.0.4) by Justin Saad
Two Factor Authentication (v1.2.22) by David Nutbourne + David Anderson, original plugin by Oskar Hane
WP Google Fonts (vv3.1.4) by Noah Kagan
WP Migrate DB (v0.9.2) by Delicious Brains
WP Offload S3 Lite (v1.2) by Delicious Brains
WP Video Lightbox (v1.8.4) by Tips and Tricks HQ, Ruhul Amin
WPBakery Visual Composer (v4.11.2.1) by Michael M - WPBakery.com
WordPress Reset (v1.4) by Matt Martz
Yoast SEO (v5.1) by Team Yoast

Must-use Plugins:
Force Strong Passwords - WPE Edition (v1.6.4) by Jason Cosper
Stop long comments (v0.0.4) by WPEngine
WP Engine System (v3.2.1) by WP Engine


Drop-ins:
advanced-cache.php - advanced-cache.php
object-cache.php - Memcached Redux
~~~~

**Comment by nazarioa** [comment] 2017-08-24 20:53
I am following up here... seems like a few people are suffering from this: [396](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/396)

**Comment by aaemnnosttv** [comment] 2017-08-25 10:04
Thanks for the offer @nazarioa. Is this issue related to # 396?

At this point, the biggest help would be to reproduce the issue on a clean, vanilla WP install. That is: fresh install of WP, only aws and Offload S3 plugins installed, using Twenty Seventeen theme, with domain mapping (if multisite). If this is possible, and we can do the same, this issue will get attention much sooner.

**Comment by lordcash** [comment] 2017-09-25 06:16
Please has this been fixed? all my files are showing access denied because of the url change.

**Comment by aaemnnosttv** [comment] 2017-09-25 09:56
@lordcash we have yet to confirm this issue with the plugin. Perhaps you could help us reproduce it?

**Comment by kpennell** [comment] 2017-12-05 22:06
Any luck here?

**Comment by ianmjones** [comment] 2017-12-06 11:37
@kpennell What's your setup and what issue are you seeing?

**Comment by kpennell** [comment] 2017-12-06 16:37
@ianmjones thanks for the response, our dev pulled the plugin.

**Comment by giobi** [comment] 2018-03-01 10:24
This issue is still happening on my network sites, has it been fixed?

**Comment by ianmjones** [comment] 2018-03-01 11:45
@giobi Can try implementing https://deliciousbrains.com/wp-offload-s3/doc/filtering-urls-for-multiple-domains/ and let us know how you get on?

**Comment by giobi** [comment] 2018-03-02 09:50
I own a multisite, shell I implement that code snippet on a custom plugin for the whole network? Should I insert all the custom domains I am using?

**Comment by giobi** [comment] 2018-03-02 20:14
For now I solved the issue with a .htaccess RewriteRule that redirects all images to s3

**Comment by ianmjones** [comment] 2018-03-05 17:07
Hey @giobi, I guess you could probably implement it at either the network or subsite level, probably doesn't matter.

However, if you did it at network level you could probably do something that simply adds the current request's domain to the list so that you only need to add the one custom plugin and not need to list every domain individually.

If you try it we'd love to hear any feedback you may have.

**Comment by giobi** [comment] 2018-03-05 19:57
I don't think I can activate it on single sites if I'm in a network.. I tried but it did not allow that option.
The .htaccess is already at network level, the rule is something like 

RewriteRule ^(.*)wp-content/uploads/sites/(.*)$ http://s3bucket..../$2 [QSA,NC,NE,R,L]

**Comment by SamirMalpande** [comment] 2018-05-30 08:10
In WP Bakery if we add a background image to any row or column, it stores the generated css in postmeta table. WP Bakery stores the shortcode's custom css in postmeta table with meta_key '_wpb_shortcodes_custom_css'. All the styles including background image urls are stored in postmeta table. While page is being generated this css is added to html head tag using wp_head action. Offload S3 replaces all the urls in content but is not able to replaces urls which are added to head.

To reproduce this issue add background image to a row or column using visual composer's backend editor. publish the post and delete the image from server but keep it in s3.

Now when we load the page you will get 404 error on page as the background-image in css is still pointing to location on server instead of S3 URL.

Reference WP Bakery code can be found in in _'js_composer\js_composer\include\classes\core\class-vc-base.php'_. In the _initPage()_ wp_head action is used with callback _addFrontCss()_

**Comment by ianmjones** [comment] 2018-05-30 10:54
@SamirMalpande The issue you've posted to is related to domain mapping on a multisite, not problems with WPBakery, please can you open a new issue if you have a reproducible bug.

Instead of opening a new issue it might be worthwhile adding your findings to #422, it may prompt us to re-open the issue if we can reproduce your problem.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.

**Comment by mrbm** [comment] 2018-08-10 06:28
I have been running into an issue that i think is related to this issue I initially posted. Been playing with Divi theme and successfully filtering. However when adding custom css via the customizer, for some reason when i have:
` background-image: url(directlinktos3);` my final out put will reference the local file that s3 file is associated with.

So with divi haven't been recently using css for background images. But now running into another problem where the thumbnails in the gallery module settings are showing the local file. which are in a situation using: background-image: url();

So i tried manually filtering the image paths, and they still go back to the local file reference.

Would you guys please test against the following scenario:

multisite
divi child theme
php 7.1
then attempt to use the customizer and add background-image: url(s3imagepath); background-image: url(localimagepath);

and see if either of those point to the right s3 file after render...if they dont then there's your bug that could be creating all these other problems.

**Comment by ianmjones** [comment] 2019-04-29 11:07
WP Offload Media Lite 2.1.1 has been released with support for the WordPress MU Domain Mapping plugin.

**Closed by ianmjones** 2019-04-29 11:07 UTC
Labels: pending dev

**Comment by mrbm** [comment] 2019-04-29 14:53
@ianmjones 

Going to check out your update, just want to note that my issue is not with Wordpress MU Domain Mapping, but is with the WPMUDEV Domain Mapping plugin. I never tested with WordPress MU Domain Mapping plugin.

**Comment by ianmjones** [comment] 2019-04-30 10:32
@mrbm Thanks for the info.

Yes, please test the new update, there's plenty other related fixes that might solve your particular problems.
