### ISSUE TITLE
New post goes to blank page

### ISSUE THREAD

**Issue by danjcarrington** [deliciousbrains/wp-amazon-s3-and-cloudfront#386] opened 2017-06-29 20:32 UTC
Hello,

We've had a Wordpress site using this amazon-s3-and-cloudfront plugin for over a year now. Recently, I upgraded Wordpress to 4.8 and did an update to all plugins and now when this plugin is enabled, when I create a post and click "Publish" it takes me to a blank page. The post does actually get published, but it shouldn't go to a blank page. If I disable this plugin, posts are published and I'm taken back to the post as it should be.

Not sure if there's a setting I'm missing or what. Any ideas?

**Comment by A5hleyRich** [comment] 2017-06-30 08:48
I wouldn't expect WP Offload S3 to cause this problem, but to confirm can you enable `WP_DEBUG_LOG` and try publishing another post? An error should be logged which will help to identify the issue:

https://codex.wordpress.org/Debugging_in_WordPress#WP_DEBUG_LOG

**Comment by danjcarrington** [comment] 2017-06-30 20:25
Ok...I enabled debug and replicated the error. The contents of the debug.log are as follows:

[30-Jun-2017 20:23:20 UTC] WP_Community_Events::maybe_log_events_response: Valid response received. Details: {"api_url":"https:\/\/api.wordpress.org\/events\/1.0\/","request_args":{"body":{"number":5,"ip":"68.98.65.0","locale":"en_US","timezone":"America\/Phoenix"}},"response_code":200,"response_body":{"location":{"ip":"68.98.65.0"},"events":"0 events trimmed."}}

**Comment by aaemnnosttv** [comment] 2017-07-03 12:10
This is an unrelated non-error log entry from the new Community Events dashboard widget.  Anything else?

**Comment by danjcarrington** [comment] 2017-07-03 14:46
Agreed. I didn't notice anything in there that seemed related. But this is all that came up when I reproduced the symptom with debugging turned on. I'll look to see if there is perhaps a way to increase the log  level to get more verbose output. Also, in case it helps, I'll log in later today and get a list of all the plugins installed. While this plugin seems to be the only one that definitively seems to trigger the symptom, I'm wondering if perhaps there is an issue with it reacting to another plugin.

**Comment by aaemnnosttv** [comment] 2017-07-03 14:50
> I'm wondering if perhaps there is an issue with it reacting to another plugin

Unfortunately, that's usually the case, which is also hard to debug and not always easy to reproduce.

If you'd like, it might help to provide the diagnostic information for your install here for us to see. This also includes a list of the active plugins.

**Comment by danjcarrington** [comment] 2017-07-03 20:05
Ok...So, just as a test, I disabled all of the plugins that I was able to and still was able to duplicate the symptom. The plugins installed are:

* Amazon Web Services
* Post List
* Print-O-Matic
* WP Offload S3 Lite
* WP RSS Aggregator

For my test, I was not able to disable Amazon Web Services as there was a dependency there.

Still going to see if there is a way to change the level of verbosity for the logs.

**Comment by aaemnnosttv** [comment] 2017-07-03 20:15
The plugins in your list here, they are active as well I assume?
Can you not disable Post LIst, Print-O-Matic, and RSS Aggregator temporarily to test?

**Comment by danjcarrington** [comment] 2017-07-03 20:18
I did disable everything except the Amazon Web Service plugin just to see if one of those plugins was interfering. There was no change in symptom. So, whether those other plugins are enabled or disabled, if the WP Offload S3 Lite is enabled, the symptom can be reproduced. If the Offload S3 plugin is disabled, the symptom is not reproduced.

**Comment by aaemnnosttv** [comment] 2017-07-04 08:04
Would you please provide the diagnostic information from the Support tab of the plugin settings?

**Comment by danjcarrington** [comment] 2017-07-07 15:13
site_url(): https://dev.discounttirefamily.com
home_url(): http://dev.discounttirefamily.com
Database Name: ebdb
Table Prefix: wp_
WordPress: 4.8
Web Server: Apache
PHP: 5.6.30
MySQL: 5.6.27
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Memory Usage: 8 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Disabled
WP_DEBUG: Yes
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 20 MB
PHP Time Limit: 60
PHP Error Log: /var/app/current/wp-content/debug.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1k-fips 8 Jan 2015
cURL: Enabled
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 409
Media Files on S3: 262
Number of Image Sizes: 5

Names and Dimensions of Image Sizes: 
thumbnail (132x150)
medium (300x300)
large (1024x1024)
post-thumbnail (none)

WP_CONTENT_DIR: /var/app/current/wp-content
WP_CONTENT_URL: http://dev.discounttirefamily.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/app/current/wp-content/plugins
WP_PLUGIN_URL: http://dev.discounttirefamily.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: 1
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: dev.uploads.discounttirefamily.com
Region: us-west-2
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
http://dev.discounttirefamily.com/wp‑content/uploads/photo.jpg
S3 URL:
https://s3‑us‑west‑2.amazonaws.com/dev.uploads.discounttirefamily.com/photo.jpg

Domain: path
Enable Path: Off
Custom Path: 
Use Year/Month: Off
Force HTTPS: Off
Remove Files From Server: Off
Object Versioning: Off

Active Theme Name: Renad
Active Theme Folder: renad

Active Plugins:
Amazon Web Services (v1.0.3) by Delicious Brains
Post List (v1.1) by vijaybidla
Print-O-Matic (v1.7.9) by twinpictures
WP Offload S3 Lite (v1.2) by Delicious Brains
WP RSS Aggregator (v4.11.1) by RebelCode

**Comment by aaemnnosttv** [comment] 2017-08-15 14:10
So far we're unable to reproduce the problem you're having. Is this still an issue for you? Where is this site hosted? Does this happen on the production site too?

**Comment by danjcarrington** [comment] 2017-08-16 22:25
It is still an issue. This is running in Amazon Web Services using Elastic Beanstalk for deployment. At the moment, I have not upgraded Wordpress on the production web site as I did not want to introduce an issue into that environment.

**Comment by danjcarrington** [comment] 2017-11-10 15:57
As a test, I tried doing a fresh install of Wordpress (rather than upgrading from the previous version). Again, if I have the "WP Offload S3 Lite" plugin active, a new post goes to a blank page. In case it helps, when this plugin is active, the URL after I publish the post is:

https://mydomain.com/wp-admin/post.php

When the plugin is deactivated, after I publish a post, the URL is:

https://mydomain.com/wp-admin/post.php?post=3539&action=edit

Not sure if that helps provide any useful info or not, but I thought I'd try.

Thanks!!

**Comment by ianmjones** [comment] 2019-03-11 12:42
We've never had anyone else with this problem, can't reproduce it, and are convinced it's something outside of WP Offload Media's control.

As such I'm closing this issue, but if anyone has the same problem and can give us cast-iron steps to reproduce that we can test with a fresh install of WordPress we'll re-open.

**Closed by ianmjones** 2019-03-11 12:42 UTC
Labels: unconfirmed
