### ISSUE TITLE
Option to upload compressed version to S3

### ISSUE THREAD

**Issue by mcdanielisaac** [deliciousbrains/wp-amazon-s3-and-cloudfront#171] opened 2014-12-05 23:40 UTC
CloudFront will only serve a compressed file if it has been included in your S3 Bucket. However, S3 will not compress the file for you. It would be an awesome feature to be able to have this plugin give the option of compressing and uploading both versions.

Heres the [info in the AWS documention](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#CompressedS3).

**Comment by treyrich2001** [comment] 2015-08-08 00:31
@polevaultweb what's the status on this request? I was about to implement this functionality as an addon plugin, but I'm wondering if this is something that you're looking to integrate into the core plugin soon?

**Comment by grappler** [comment] 2015-10-25 07:34
Duplicate of https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/283

@mcdanielisaac & @treyrich If you are still interested I have some code that I wrote for svg files: https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/283#issuecomment-149036957

**Closed** 2015-11-25 09:25 UTC
