### ISSUE TITLE
Resizing + versioning images

### ISSUE THREAD

**Issue by cR0Ckr0x** [deliciousbrains/wp-amazon-s3-and-cloudfront#358] opened 2016-12-21 02:44 UTC
Hello,
I read all the documentation and issues and could still not solve these (I suppose common) issues:

- Only sources of images uploaded on S3 are stored. No versions (thumbnail, medium, large) can be found on my S3 Bucket. How can I make these available to be used on the site? (It would be contraddictory to use S3 to reduce bandwidth but serving only biggest assets) - also when using an ephemeral file system like my case, it is obviously necessary to have all version stored in the bucket.
- A screenshot from my iPad is 8MB in size, and a photo about half. I'd like to auto resize uploaded media to a max of 2048x2048 and compress images. I tried several but could not find any wordpress plugin compatible with S3 Offload. Also a client-side resizer plugin would be very interesting.

Thank you

**Comment by A5hleyRich** [comment] 2016-12-22 12:51
All sizes registered with `add_image_size` should be offloaded to S3. 

https://developer.wordpress.org/reference/functions/add_image_size/

Can you post the contents of your diagnostic information, found from the Support tab?

**Comment by aaemnnosttv** [comment] 2017-06-27 19:59
Thanks for your feedback. We do a lot of testing to make sure all registered image sizes are offloaded and served from S3 just as the source images are.  If you're not seeing that then the most likely cause is a plugin or theme conflict.

Regarding the auto-resizing, WordPress does this already using image sizes. You could always register an image size to be the largest size you want, and then reference that size in your code instead of `full`. Regarding a plugin to do this at upload time, [Maximum Image Size](https://wordpress.org/plugins/maximum-image-size/) may be what you're looking for (it replaces the original with the `large` size).

**Comment by Chinese1904** [comment] 2017-06-29 20:01
I am experiencing the same issue that resized images/thumbnails are not being uploaded to S3. My support tab information is as follows:

```
site_url(): https://kinesiologyinstitute.com
home_url(): https://kinesiologyinstitute.com
Database Name: kinesio2_database
Table Prefix: wp_
WordPress: 4.8
Web Server: Apache
PHP: 7.0.20
MySQL: 5.5.5
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Memory Usage: 72 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 5 GB
PHP Time Limit: 300
PHP Error Log: error_log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1e-fips 11 Feb 2013
cURL: Enabled
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 149
Media Files on S3: 6
Number of Image Sizes: 16

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
shop_thumbnail (180x180)
shop_catalog (300x300)
shop_single (600x600)
tt_post_icon (100x100)
tt_featured_thumbnail (220x220)
tt_extended_menu (250x100)
tt_related_posts (350x225)
tt_post_gallery (325x390)
tt_grid_layout (360x300)
tt_featured_wide_sidebar (665x365)
tt_featured_wide_narrow (617x340)
tt_featured_wide_full (1130x570)

WP_CONTENT_DIR: /home/kinesio2/public_html/wp-content
WP_CONTENT_URL: https://kinesiologyinstitute.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /home/kinesio2/public_html/wp-content/plugins
WP_PLUGIN_URL: https://kinesiologyinstitute.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: kinesiology-instititue
Region: us-east-2
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
https://kinesiologyinstitute.com/wp‑content/uploads/2017/06/photo.jpg
S3 URL:
https://s3‑us‑east‑2.amazonaws.com/kinesiology‑instititue/wp‑content/uploads/2017/06/29195836/photo.jpg

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: Off
Remove Files From Server: On
Object Versioning: On

Active Theme Name: Pressive
Active Theme Folder: pressive

Active Plugins:
AddToAny Share Buttons (v1.7.11) by AddToAny
Amazon Web Services (v1.0.3) by Delicious Brains
Booked (v2.0) by Boxy Studio
Booked Add-On: Calendar Feeds (v1.1.1) by Boxy Studio
Booked Add-On: Front-End Agents (v1.1.14) by Boxy Studio
Booked Add-On: WooCommerce Payments (v1.4.4) by Boxy Studio
Custom Sidebars (v3.0.8.1) by WPMU DEV
Google Analytics Dashboard for WP (GADWP) (v5.0.1) by Alin Marcu
InfusedWoo Pro (v3.7.6) by Mark Joseph
LearnDash LMS (v2.4.5) by LearnDash
Page as Subdomain Free (v1.5.0) by alisaleem252
SparkPost (v3.0.1) by SparkPost
Subscriptio (v2.3.8) by RightPress
The Events Calendar (v4.5.7) by Modern Tribe, Inc.
Thrive Clever Widgets (v1.29) by Thrive Themes
Thrive Headline Optimizer (v1.1.7) by Thrive Themes
Thrive Leads (v1.95.20) by Thrive Themes
Thrive Ovation (v1.0.16) by Thrive Themes
Thrive Quiz Builder (v1.0.13) by Thrive Themes
Thrive Ultimatum (v1.5.19) by Thrive Themes
Thrive Visual Editor (v1.500.19) by Thrive Themes
UpdraftPlus - Backup/Restore (v1.13.4) by UpdraftPlus.Com, DavidAnderson
WP Add Custom CSS (v1.0.1) by Daniele De Santis
WP Offload S3 Lite (v1.2) by Delicious Brains
WooCommerce (v3.1.0) by Automattic
WooCommerce Deposits (v1.3.0) by Automattic
WooCommerce Dynamic Pricing & Discounts (v2.0) by RightPress
WooCommerce Google Analytics Integration (v1.4.3) by WooCommerce
WooCommerce PayPal Powered by Braintree Gateway (v2.0.3) by WooCommerce
Wordfence Security (v6.3.12) by Wordfence
Yoast SEO (v4.9) by Team Yoast
```

Can you see anything what could cause this conflict?

**Comment by A5hleyRich** [comment] 2017-06-30 08:46
@Chinese1904 nothing stands out from the diagnostic information. Please can you provide example filenames that aren't upload to S3?

**Comment by Chinese1904** [comment] 2017-06-30 17:04
Volcano-into-the-ocean-150x100.jpg 
AKS-Part-1-31-300x225.png

Failed to load resource: the server responded with a status of 404 (Not Found)

Those are two examples.

Thanks for your help and the swift response!

**Comment by ianmjones** [comment] 2017-07-03 10:00
@Chinese1904 Can you try editing your wp-config.php file to replace this line -

define( 'WP_DEBUG', false );

With these lines -

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);

This means that any errors are logged to `/wp-content/debug.log`, because some errors are not visible on screen. More details about that at http://codex.wordpress.org/Editing_wp-config.php#Debug

Can you try the process again and check the `debug.log` file for errors please.

**Comment by Chinese1904** [comment] 2017-07-26 03:28
```
[26-Jul-2017 03:24:27 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:27 UTC] PHP Warning:  filesize(): stat failed for /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png in /home/kinesio2/public_html/wp-content/themes/pressive/kraken-callback.php on line 47
[26-Jul-2017 03:24:29 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:30 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:32 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:32 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:33 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:33 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:35 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:36 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:36 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:37 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:38 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:40 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:40 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:41 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
[26-Jul-2017 03:24:44 UTC] WPOS3: File /home/kinesio2/public_html/wp-content/uploads/2017/07/AKS-Part-1-3-test.png does not exist
```
 Sorry for the late reply, either way that's the debug log.

The original file I try uploading is https://s3-us-east-2.amazonaws.com/kinesiology-instititue/wp-content/uploads/2017/07/26032426/AKS-Part-1-3-test.png

If this error looks familiar then I would definitely appreciate a hint towards the solution as I would love to use this plugin again. But I will research myself now as well. If I find a solution I will let you know where it went wrong

**Comment by ianmjones** [comment] 2017-07-26 09:41
@Chinese1904 said:
> Is there any fix for this so I can remove the files from the server using this plugin, without it deleting the uploaded file before it is done being worked with / converting all the resized images?

That's how it's supposed to work already, nothing should get uploaded to S3 until WP has finished processing the sizes and updates the metadata to log which sizes are available for the image. The files are only removed from the local server once copied to S3.

Can you give detailed steps to reproduce, given your reference to #388 it sounds like you may be getting the error when updating an image via the Media Library editor, correct? Or is it when adding a new image to a post via the Post editor?

**Comment by Chinese1904** [comment] 2017-07-28 16:54
Thanks for assistance. I never get to the point of editing them, because there aren't any converted thumbnails being uploaded at all. So, this happens when I upload new media using the library.

**Comment by ianmjones** [comment] 2017-07-31 10:08
@Chinese1904 I have a hunch that something in your setup is interfering with the upload process.

Please can you try switching to one of the default WordPress themes (e.g. Twenty Sixteen), try the process of uploading a new media library item again, and then you can switch back to your current theme afterwards.

**Comment by ianmjones** [comment] 2018-02-09 11:20
No further info provided, closing.

**Closed by ianmjones** 2018-02-09 11:20 UTC
