### ISSUE TITLE
Bug: Rankmath Site Maps Not filtering image urls

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#629] opened 2023-05-08 17:43 UTC
**Describe the bug**
When using the rankmath plugin and Divi theme,  sitemap seems to be showing the urls of local paths instead the remote paths.

**To Reproduce**
Install https://wordpress.org/plugins/seo-by-rank-math/
Activate sitemaps plugin
Create a new page that has images (currently doing this via the divi theme)
Review the site map source code generated

**Expected behavior**
Expect to see the image paths filtered to the correct remote url, but instead seeing the local url

**Diagnostic Info (from plugin's "Support" tab):**
site_url(): https://PRIVATE.PRIVATE.com
home_url(): https://PRIVATE.PRIVATE.com
Database Name: PRIVATE-wp-rhQUsf1new
Table Prefix: wp_
WordPress: 6.2 Multisite (subdirectory)
Multisite Site Count: 15
Domain Mapping: Enabled
Web Server: Apache/2.4.57 (Unix) OpenSSL/1.1.1
PHP: 7.4.33
MySQL: 5.7.41
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 64M
Memory Usage: 2 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 14 MB
PHP Time Limit: 30
PHP Error Log: /srv/users/serverpilot/log/PRIVATE/PRIVATE_php7.4.error.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.1.1  11 Sep 2018
cURL: 7.58.0
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Total Media Items: 1,888
Total Offloaded Media Items: 389
Total Not Offloaded Media Items: 1,499

Media Library Items: 1,888
Offloaded Media Library Items: 389
Not Offloaded Media Library Items: 1,499

Number of Image Sizes: 16

Names and Dimensions of Image Sizes:
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)
et-pb-post-main-image (400x250)
et-pb-post-main-image-fullwidth (1080x675)
et-pb-portfolio-image (400x284)
et-pb-portfolio-module-image (510x382)
et-pb-portfolio-image-single (1080x9999)
et-pb-gallery-module-image-portrait (400x516)
et-pb-post-main-image-fullwidth-large (2880x1800)
et-pb-image--responsive--desktop (1280x720)
et-pb-image--responsive--tablet (980x551)
et-pb-image--responsive--phone (480x270)

WP_CONTENT_DIR: /srv/users/serverpilot/apps/PRIVATE/public/wp-content
WP_CONTENT_URL: https://PRIVATE.PRIVATE.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /srv/users/serverpilot/apps/PRIVATE/public/wp-content/plugins
WP_PLUGIN_URL: https://PRIVATE.PRIVATE.com/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Not defined

Local URL:
https://PRIVATE.PRIVATE.com/wp-content/uploads/2023/05/example.jpg
Offload URL:
https://PRIVATE2.PRIVATE2.com/wp-content/uploads/2023/05/08173030/example.jpg

OME Metadata Version: 12

Custom tables:
wp_as3cf_items: Ok

Storage Provider: Amazon S3
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: AWS_ACCESS_KEY_ID
Secret Access Key Define: AWS_SECRET_ACCESS_KEY

Bucket: PRIVATE2.PRIVATE2.com
Region: us-west-1
Block All Public Access: Disabled
Object Ownership Enforced: No

Offload Media: On
Remove Local Media: On
Enable Add Prefix to Bucket Path: On
Custom Prefix for Bucket Path: wp-content/uploads/
Add Year & Month to Bucket Path: On
Add Object Version to Bucket Path: On

Delivery Provider: Cloudflare
Deliver Offloaded Media: On
Use Custom Domain Name (CNAME): On
Custom Domain (CNAME): PRIVATE2.PRIVATE2.com

Force HTTPS: On

Active Theme Name: DIVI CHILD
Active Theme Version: v1.0
Active Theme Folder: DIVI CHILD
Parent Theme Name: Divi
Parent Theme Version: 4.20.4
Parent Theme Folder: Divi

Active Plugins:
Akismet Anti-Spam (v5.1) by Automattic
Defender Pro (v3.10.1) by WPMU DEV
Disable WP REST API (v2.5) by Jeff Starr
Divi Accessibility (v2.0.5) by CampusPress
Domain Mapping (v4.4.3.3) by WPMU DEV
Bunny Check for user admin rights (vv 1.0) by Ben M
Cloudflare Network Clear (vv 1.0) by Ben M
Snapshot Pro (v4.16.0) by WPMU DEV
Sucuri Security - Auditing, Malware Scanner and Hardening (v1.8.39) by Sucuri Inc.
WP Offload Media Lite (v3.2.1) by Delicious Brains
WPMU DEV Dashboard (v4.11.18) by WPMU DEV

Must-use Plugins:
API Load Time Enhancement (v007) by Ben
ET Support Center :: Must-Use Plugins Autoloader (v) by Elegant Themes
Fix Visual Builder Edit Link (vv 1.0) by Ben M
Plugin Adjustments (vv 1.0) by Ben M
Remove Network Orders (vv 1.0) by Ben M

Drop-ins:
sunrise.php - sunrise.php

**Comment by ianmjones** [comment] 2024-04-15 09:12
Duplicate of #593

**Closed by ianmjones** 2024-04-15 09:12 UTC
Labels: bug
