### ISSUE TITLE
Background-image url CSS from Visual Composer not pointing to S3 

### ISSUE THREAD

**Issue by RavenHursT** [deliciousbrains/wp-amazon-s3-and-cloudfront#422] opened 2017-12-21 00:45 UTC
Looks like there's someone else came across this issue a few weeks ago: https://wordpress.org/support/topic/background-image-configured-for-a-row-using-visual-composer-doesnt-work/

What's _really_ odd, is that the urls inside of the VC editing interface, DO reference the images that have been pushed up to S3.  But when the CSS for the page is rendered, the urls in the CSS are referencing the local server images.

Does anyone have any idea why this would be?

**Comment by RavenHursT** [comment] 2017-12-21 00:47
Here's another person seeing the same problem: https://wordpress.org/support/topic/url-rewrite-issue-with-visual-composer/

**Comment by DesigningStudios** [comment] 2017-12-26 20:10
I am also facing same issue 👍

**Comment by odis912** [comment] 2018-01-02 04:47
me too

**Comment by binhqx** [comment] 2018-01-26 15:41
Also have this issue and I'm looking into it.

**Comment by alanmcginnis** [comment] 2018-02-21 21:02
Having the same issue.

**Comment by not-original** [comment] 2018-02-26 18:03
Same here

**Comment by alanmcginnis** [comment] 2018-03-20 02:14
Looks like this is being worked on but I am having the same issue. If there is any data I can provide please let me know. For now my fix is to use on page CSS to set the background image.

**Comment by georgenicholas** [comment] 2018-04-24 17:25
Same issue here.

**Comment by ianmjones** [comment] 2018-05-11 15:30
Hey peeps,

So I've been trying to reproduce this problem with background images on Visual Composer rows not using the S3 URL when displayed to a visitor, and have failed miserably, yay! ;-)

I can add images before or after being offloaded, available locally or not, all happily filter to the S3 URL in both the editor and on page display.

Can someone please provide cast iron detailed steps to reproduce on a clean install of WordPress with just WP Offload S3 and Visual Composer installed?

Cheers,

Ian

**Comment by ianmjones** [comment] 2018-05-23 12:05
Closing as unable to reproduce.

**Comment by itsmrwalsh** [comment] 2018-06-22 09:44
I can confirm that @SamirMalpande's method of replicating this works. I've got multiple pages with 404ing background images from this exact process.

**Comment by ianmjones** [comment] 2018-06-25 09:48
Thanks for the feedback @SamirMalpande and @itsmrwalsh, we'll see if we can reproduce and fix this in a future release.

**Comment by DSaxon** [comment] 2018-06-27 19:08
I have been having the same issue would love to know if any solutions were identified

**Comment by florent-a1969** [comment] 2018-06-29 12:20
Same issue. +1 for a solution

**Comment by itsmrwalsh** [comment] 2018-06-29 13:32
@DSaxon for now, the only workaround I've found is to keep a copy of your media in your media library on your server and re-upload any background images you'd offloaded.

**Comment by fizcoder** [comment] 2018-07-03 22:48
I can confirm I am also experiencing the same issue.

Keeping a copy on the server isn't an option for me.

**Comment by ianmjones** [comment] 2018-07-04 10:32
Please add a 👍 reaction to this post if you're having an issue with background images in **Visual Composer** as downloaded from https://visualcomposer.io/

**Comment by ianmjones** [comment] 2018-07-04 10:32
Please add a 👍 reaction to this post if you're having an issue with background images in **WPBakery Page Builder (formerly Visual Composer)** as downloaded from https://wpbakery.com/

**Comment by itsmrwalsh** [comment] 2018-08-02 08:33
@ianmjones Any updates on this? I've got clients losing patience with the workaround I have in place.

Thanks.

**Comment by ianmjones** [comment] 2018-08-02 08:55
@itsmrwalsh I've tried to contact WPBakery a couple of times over the last month via their Slack to see whether we can work on a fix together, no response.

If you have their ear, maybe you'll be able to point them in my direction.

**Comment by arleyandrada** [comment] 2018-08-21 04:10
`function as3cf_filter_get_post_metadata( $metadata, $object_id, $meta_key, $single ) {
    $meta_filter = array('_wpb_shortcodes_custom_css', '_wpb_post_custom_css');
    if ( isset( $meta_key ) && $single && in_array($meta_key, $meta_filter)) {
        remove_filter( 'get_post_metadata', 'as3cf_filter_get_post_metadata', 100 );
        $metadata = get_post_meta( $object_id, $meta_key, $single );
        add_filter('get_post_metadata', 'as3cf_filter_get_post_metadata', 100, 4);
        $metadata = apply_filters( 'as3cf_filter_post_local_to_s3', $metadata );
    }
    return $metadata;
}
add_filter( 'get_post_metadata', 'as3cf_filter_get_post_metadata', 100, 4 );`

**Comment by epoplive** [comment] 2018-09-04 18:01
I am also seeing this issue and would really like to see a fix.

**Comment by elektra3** [comment] 2018-09-05 06:56
Any updates on this issue?
Very frustrating when you're trying to add background images, especially parallax...

**Comment by itsmrwalsh** [comment] 2018-09-05 11:03
@ianmjones - I have their ear on this no more than you do I'm afraid. 

@arleyandrada - Assuming this is a solution that works for you? I'll give it a go and report back.

**Comment by itsmrwalsh** [comment] 2018-09-05 11:39
@ianmjones - I can confirm that the function @arleyandrada wrote is working for me with VC background images.

**Comment by arleyandrada** [comment] 2018-09-05 11:58
Yes, it is a solution to the problem, with relatively low impact for future plug-in updates. Sorry for the comment without any description. @itsmrwalsh @ianmjones @epoplive @elektra3

**Comment by alanmcginnis** [comment] 2018-09-05 20:57
@arleyandrada Any where I can buy you a beer?

**Comment by arleyandrada** [comment] 2018-09-05 21:36
Yes, I accept a beer! @alanmcginnis

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=VGKB3U95YYZSE)

Thanks!

**Comment by not-original** [comment] 2018-09-07 16:32
Thank you for this!!!

**Comment by egantz** [comment] 2019-02-01 22:14
@arleyandrada GOLDEN.

**Comment by georgenicholas** [comment] 2019-05-16 16:02
@arleyandrada Thank you!

**Comment by gerardfollano** [comment] 2019-08-15 08:54
@arleyandrada do you have an updated version of your code? I updated my plugins and now the code is not working correctly.... Thanks!

**Comment by gerardfollano** [comment] 2019-08-15 20:46
> @arleyandrada do you have an updated version of your code? I updated my plugins and now the code is not working correctly.... Thanks!

NVM. This was a url error on my end when i transferred my site to a new domain name. Everything still works as expected on the latest version.

**Comment by maharjanrams** [comment] 2020-01-10 04:50
@arleyandrada thanks mate.

**Comment by sacgrover** [comment] 2020-10-23 07:29
> ```
> function as3cf_filter_get_post_metadata( $metadata, $object_id, $meta_key, $single ) {
>     $meta_filter = array('_wpb_shortcodes_custom_css', '_wpb_post_custom_css');
>     if ( isset( $meta_key ) && $single && in_array($meta_key, $meta_filter)) {
>         remove_filter( 'get_post_metadata', 'as3cf_filter_get_post_metadata', 100 );
>         $metadata = get_post_meta( $object_id, $meta_key, $single );
>         add_filter('get_post_metadata', 'as3cf_filter_get_post_metadata', 100, 4);
>         $metadata = apply_filters( 'as3cf_filter_post_local_to_s3', $metadata );
>     }
>     return $metadata;
> }
> add_filter( 'get_post_metadata', 'as3cf_filter_get_post_metadata', 100, 4 );
> ```

Thanks for the Solution!!

**Comment by chriscooning** [comment] 2021-01-27 23:34
If anyone struggled on where to put this snippet of code (like I did for a bit... 🤪)  it's found under the wp offload plugins directory: amazon-s3-and-cloudfront/include/functions.php

Slap that snippet @arleyandrada provided into the bottom of that file and you're good to go! 👍

**Comment by ianmjones** [comment] 2021-01-28 10:02
@chriscooning That's the wrong place to put that code.

The include/functions.php file for WP Offload Media Lite will get overwritten on each new release of the plugin, so you'll lose your changes each time a plugin update is released.

The code should go in your **child** theme's functions.php file.

A child theme is fully under your control, and lets you get updates to the main theme without overwriting anything in your child theme. It's always a good idea to use a child theme rather than stock theme from wp.org or anywhere else.

https://developer.wordpress.org/themes/advanced-topics/child-themes/

**Comment by NaitikKundalia** [comment] 2021-05-31 18:06
I have the same issue. I tried the solution which was given by @arleyandrada . I had put it inside the plugin's function.php file.  But it is not working.  I don't know what type of info you need to solve this query. So tell me what is required and I will upload it.

Is this code not work in new version?

**Comment by ianmjones** [comment] 2021-06-29 11:25
We're keeping track of votes for integrating with page builders and other plugins that have custom content handling that does not use the standard WordPress functionality and therefore prevents WP Offload Media's URL rewriting hooks from firing.

However, because of the work involved in developing, testing and maintaining such integrations, we generally add such integrations to WP Offload Media rather than WP Offload Media Lite.

**Closed by ianmjones** 2021-06-29 11:25 UTC
Labels: unconfirmed
