### ISSUE TITLE
Network admin slowness and timeouts after upgrade to 1.1.4

### ISSUE THREAD

**Issue by dpegasusm** [deliciousbrains/wp-amazon-s3-and-cloudfront#357] opened 2016-12-20 21:57 UTC
After upgrading to 1.1.4 any of the screens in the network admin area of WP take a very long time to load. A debug on this traces it back to the aws_init hook and only happens on the network admin screens and not on the regular admin screens or frontend. 

![screen shot 2016-12-20 at 1 20 17 pm](https://cloud.githubusercontent.com/assets/2442680/21368652/82dd25f4-c6d1-11e6-9c1a-8fdcc4c1ed83.png)

**Comment by guillaumemolter** [comment] 2016-12-21 14:53
I work with @dpegasusm. This is what we see in New Relic:

![screen shot 2016-12-21 at 09 19 02](https://cloud.githubusercontent.com/assets/1478527/21393609/2fd07b12-c763-11e6-8ed8-c2dd7d6c8621.png)

![screen shot 2016-12-21 at 09 16 41](https://cloud.githubusercontent.com/assets/1478527/21393613/3418a1f4-c763-11e6-9f8a-172e732fa7b5.png)

Reverting to 1.1.3 is fixing the issue.

**Comment by A5hleyRich** [comment] 2016-12-22 12:47
It looks like one of the upgrade routines is trying to run, but that shouldn't happen if you've already had WP Offload S3 installed for a while. If you check your `tantan_wordpress_s3` option in the sitemeta table, what is the value of `post_meta_version`?

**Comment by banago** [comment] 2017-01-05 14:58
I had the same issue on a site with 60k images and it slowed the heck down making the site unusable in backend. I ran Query Logger plugin and it shows that the plugin hit the `wp_options` table thousands of time, basically for every un-updated image. 

I worked around it by hackig the plugin file `as3cf-file-sizes.php` at these lines: https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/upgrades/as3cf-file-sizes.php#L179

      // I changed $limit from null to 10
      protected function get_s3_attachments( $prefix, $limit = 10 ) {
                global $wpdb;

                $sql = "SELECT pm1.`post_id` as `ID`, pm1.`meta_value` AS 's3object'
                                FROM `{$prefix}postmeta` pm1
                                        LEFT OUTER JOIN `{$prefix}postmeta` pm2
                                        ON pm1.`post_id` = pm2.`post_id`
                                        AND pm2.`meta_key` = 'wpos3_filesize_total'
                                WHERE pm1.`meta_key` = 'amazonS3_info'
                                AND pm2.`post_id` is null LIMIT 10";
                // I commented this
                /* if ( ! is_null( $limit ) ) {
                        $sql .= ' LIMIT %d';

                        $sql = $wpdb->prepare( $sql, $limit );
                }*/

                return $wpdb->get_results( $sql, OBJECT );
        }

So, I basically I added a `$limit = 10` because when it is `null` it processes all the images, which is a huge problem for websites with many images.

This is urgent addressing. **If you have a big site with many images, don't upgrade.**

**Comment by guillaumemolter** [comment] 2017-01-27 14:18
@A5hleyRich 
```
a:15:{s:17:"post_meta_version";i:1;s:6:"bucket";s:4:"XXXX";s:6:"region";s:0:"";s:6:"domain";s:10:"cloudfront";s:7:"expires";s:1:"1";s:10:"cloudfront";s:20:"XXXX.domain.com";s:13:"object-prefix";s:19:"wp-content/uploads/";s:10:"copy-to-s3";s:1:"1";s:13:"serve-from-s3";s:1:"1";s:17:"remove-local-file";s:1:"0";s:12:"hidpi-images";s:1:"0";s:17:"object-versioning";s:1:"0";s:21:"use-yearmonth-folders";s:1:"1";s:20:"enable-object-prefix";s:1:"1";s:11:"force-https";b:1;}``` 

Remarks:
- I have obfuscated our bucket name and cloudfront URL
- This is the value `tantan_wordpress_s3` after reverting to 1.1.3. Do you need me to put back 1.1.5 and give you the updated version?

**Comment by banago** [comment] 2017-02-07 15:49
@A5hleyRich my post meta version is 1, where in staging site is 3. On staging site the issue is not happening? What do you suggest?

**Comment by nerrad** [comment] 2017-03-02 18:51
We're seeing something similar on our multisite install after upgrading from 1.1.3 to 1.1.5.  Our network admin has slowed to a crawl and we see a large number of these types of queries:

```
SELECT pm1.`post_id` as `ID`, pm1.`meta_value` AS 's3object' FROM `ss540_postmeta` pm1 LEFT OUTER JOIN `ss540_postmeta` pm2 ON pm1.`post_id` = pm2.`post_id` AND pm2.`meta_key` = 'wpos3_filesize_total' WHERE pm1.`meta_key` = 'amazonS3_info' AND pm2.`post_id` is null"
```

We have 10k plus subsites, it looks like each request to the network admin is resulting in a new batch of subsites run through these queries.

Tracing the query reveals that it is generated by `\AS3CF_Upgrade_File_Sizes::get_s3_attachments`.

I'm guessing this has something to do with the "attachment" upgrade process introduced in 1.1.5.  But is that supposed to be happening on user facing requests?

**Comment by nerrad** [comment] 2017-03-02 19:05
I'm curious why this upgrade routine is running off of hits to the network admin as opposed to just kicking off an update when the admin individual subsite in the multisite install is visited?  There's a couple things I see happening here that may be contributing to the slowdown (very rough stack):

1. To setup the blogs to process there is a query first to get all blogs already processed (which could be a large amount).
2. Then a query to get all the blog_ids from the `*_blogs` table that haven't been processed.
3. Then the blog ids are used to generate correct prefixes for the individual blog tables.
4. Then prefixes are looped through and used to generate the query for each blog and do any upgrade stuff needed.

All of the _above_ steps have impact on loading time as the number of sites in a multisite install increase.  I imagine things would work better if upgrades are only performed when the admin of _each_ site is hit.  Then there has to be no awareness of how many sites there are in the rest of the network and things can just process _for that site_ (thus reducing the overall impact).

Thoughts?

Also, I see these filters:

```
$limit     = apply_filters( 'as3cf_update_' . $this->upgrade_name . '_batch_size', 500 );
$all_limit = $limit;
$finish    = time() + apply_filters( 'as3cf_update_' . $this->upgrade_name . '_time_limit', 20 );
```

I'm assuming changing those values might help with load time?

**Comment by nerrad** [comment] 2017-03-02 19:46
So after reviewing all the generated queries on loading the admin page (via adding debugging to the `query` filter and writing to a log), this upgrade routine is looping through every blog doing the type of query I already posted here on _each_ network admin page request.

**Comment by nerrad** [comment] 2017-03-02 19:55
k so in `AS3CF_Upgrade::maybe_init`, in a network site environment, it gets to:

```
// Do we actually have attachments to process?
// Do we actually have attachments to process?
if ( 0 === $this->count_items_to_process() ) {
	$this->upgrade_finished();

	return false;
}
```

Which for `\AS3CF_Upgrade_File_Sizes::count_items_to_processes` ends up looping through all the sites on the server and doing the above queries.  That's nuts.  On every page load?  At a minimum it should happen once and then maybe save it as a part of an option so that its only run when needed?

**Comment by nerrad** [comment] 2017-03-02 20:20
Also, in the query being done, the last part of the query doesn't seem right:

```
AND pm2.`post_id` is null
```

shouldn't that be:

```
AND pm2.`post_id` is not null
```
?

**Comment by A5hleyRich** [comment] 2017-03-02 21:00
A temp fix for this is to bump the post_meta_version to 6, which should stop the excessive load times. We're looking into this issue and will hopefully have a fix soon.

**Comment by guillaumemolter** [comment] 2017-03-07 21:54
@A5hleyRich bumping `tantan_wordpress_s3` post_meta_version to 6 had no effect in our case.

Current version:
`a:15:{s:17:"post_meta_version";i:6;s:6:"bucket";s:4:"hsph";s:6:"region";s:0:"";s:6:"domain";s:10:"cloudfront";s:7:"expires";s:1:"1";s:10:"cloudfront";s:20:"XXXXX";s:13:"object-prefix";s:19:"wp-content/uploads/";s:10:"copy-to-s3";s:1:"1";s:13:"serve-from-s3";s:1:"1";s:17:"remove-local-file";s:1:"0";s:12:"hidpi-images";s:1:"0";s:17:"object-versioning";s:1:"0";s:21:"use-yearmonth-folders";s:1:"1";s:20:"enable-object-prefix";s:1:"1";s:11:"force-https";b:1;}`

**Comment by nerrad** [comment] 2017-03-08 00:01
Just to give an update, bumping `tantan_wordpress_s3` did help things a _bit_ in our case (about 5-6s load time), but we discovered that there were queries from another plugin that were causing the majority of the load time for us.

**Comment by aaemnnosttv** [comment] 2017-04-19 08:05
This should be fixed in the next release. In the meantime, please try this branch: https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/tree/temp-fix-big-queries-before-upgrades

**Comment by guillaumemolter** [comment] 2017-04-26 20:27
@aaemnnosttv looking good on our staging env. We are going to update and hot patch prod tonight. If you don't here back from me or @dpegasusm it means it worked :-).

**Comment by aaemnnosttv** [comment] 2017-06-27 19:40
This should be no longer an issue as of v1.2. Let us know if you're still having any issues with performance.

**Closed by aaemnnosttv** 2017-06-27 19:40 UTC
