### ISSUE TITLE
Started getting 404 on my images - Local->S3 url conversion not working because of wrong variable

### ISSUE THREAD

**Issue by fabiolrs** [deliciousbrains/wp-amazon-s3-and-cloudfront#396] opened 2017-08-22 15:25 UTC
For some reason, some old posts I have started getting 404s.

After further inspection, I realized that in my database, the posts' images are saved with my local URL, for example:

`
http://testing.com/wp-content/uploads/7/testing.jpg
`

But when I edit the post, the source code on the rich text editor shows the S3 URLs, as it should.

When I save the post, it converts back the img src URLs to my local server before saving to the database.

The problem is converting it back when showing on the browser.

On as3cf-filter.php, the function replace_urls() tries to convert it back to the S3 URLs when showing on the browser, but the problem I see is here:

```
foreach ( $url_pairs as $find => $replace ) {
			$replace = $this->normalize_replace_value( $replace );
			$content = str_replace( $find, $replace, $content );
		}
```

The $find variable is actually a string, and when I have multiple images on the post, this is what this variable looks like:

`
//testing.com/wp-content/uploads/7///testing.com/wp-content/uploads/8//testing.com/wp-content/uploads/3
`

It concatenates all the img src urls on a single string, so the str_replace never works, the images URLs are not being replaced thus keeping my local server URL. Since the local images don't exit they are never found on the server and I started getting 404s.

Since I don't have much time to fiddle with the code, I actually just DISABLED the conversion of S3->local when saving the post.

On the as3cf-s3-to-local.php, I commented lines 17, 18 and 19, effectively turning off the hooks that make the plugin convert the S3 to my local environment URL. Since that conversion never happens, the conversion from local to S3 is never necessary.

I would appreciate some help on how to permanently solve this. Thanks!

**Comment by fabiolrs** [comment] 2017-08-22 15:26
Also, I am using 1.2

**Comment by aaemnnosttv** [comment] 2017-08-23 10:48
Please restore your plugin modifications to the original code (or just re-install them). Then try this:

- Delete all post meta where `meta_key` = `amazonS3_cache`, as well as the option by the same name.
- Enable `WP_DEBUG` and `WP_DEBUG_LOG` constants.
- Test saving the post again, and viewing it in the browser.

Let us know what you get and include the `wp-content/debug.log` file for us here if it doesn't work as expected.

**Comment by fabiolrs** [comment] 2017-08-23 15:01
Did all that, same problem continues to happen.

Only line added to the debug.log file was this

`[23-Aug-2017 14:57:33 UTC] PHP Notice:  Undefined property: stdClass::$theme in /opt/bitnami/apache2/htdocs/site/wp-admin/includes/class-wp-automatic-updater.php on line 275`

**Comment by lordcash** [comment] 2017-09-25 06:18
Please what is the solution to this, My blog is suffering terribly because of this.

**Comment by aaemnnosttv** [comment] 2017-09-25 09:52
@lordcash Can you provide us with steps as to how to reproduce this with a vanilla WordPress install using the latest version of WP Offload S3 Lite?

If you are a license holder, you can always reach out to us through the support form within the plugin and we'd be happy to help you troubleshoot the issue.

**Comment by rafaelveiga** [comment] 2017-12-24 22:19
Hi everyone! I'm having the same issue here.

I was able to detect that everything that matched my Cloudfront URL in my content was being replaced by Wordpress local server URL, even if the URL was outside `<img src="">` tag.

I've kinda 'brute forced' a workaround, but I'm not a PHP expert, so I'm asking for the mantainers to look deeper into this issue. 

What I did was: 
- I've commented lines 393~446 from the `classes/as3cf-filter.php` file. 
- Removed the `wp-image-XXXX` that was auto inserted by Wordpress.

Of course this is not a solution, but I hope this gives pointers to the maintainers on how to fix this bug. 

My diagnostic info:
```
site_url(): http://localhost/wordpress
home_url(): http://localhost/wordpress
Database Name: wordpress
Table Prefix: wp_
WordPress: 4.9.1
Web Server: Apache/2.2.31 (Win32) DAV/2 mod_ssl/2.2.31 OpenSSL/1.0.2e mod_fcgid/2.3.9 mod_wsgi/3.4 Python/2.7.6 PHP/7.0.9 mod_perl/2.0.8 Perl/v5.16.3
PHP: 7.0.9
MySQL: 5.5.49
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 40M
Memory Usage: 2 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 2 MB
PHP Time Limit: 30
PHP Error Log: C:/MAMP/logs/php_error.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.2e 3 Dec 2015
cURL: Enabled
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 4
Media Files on S3: 4
Number of Image Sizes: 6

Names and Dimensions of Image Sizes: 
thumbnail (none)
medium (none)
large (none)
twentyseventeen-featured-image (2000x1200)
twentyseventeen-thumbnail-avatar (100x100)

WP_CONTENT_DIR: C:\MAMP\htdocs\wordpress/wp-content
WP_CONTENT_URL: http://localhost/wordpress/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: C:\MAMP\htdocs\wordpress/wp-content/plugins
WP_PLUGIN_URL: http://localhost/wordpress/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: draft5
Region: sa-east-1
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
http://localhost/wordpress/wp‑content/uploads/2017/12/photo.jpg
S3 URL:
https://static.draft5.gg/news/2017/12/24221825/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: news/
Use Year/Month: On
Force HTTPS: On
Remove Files From Server: On
Object Versioning: On

Active Theme Name: Twenty Seventeen
Active Theme Folder: twentyseventeen

Active Plugins:
Amazon Web Services (v1.0.4) by Delicious Brains
Only One Category (v1.0.4) by Press Up
WP Offload S3 Lite (v1.2.1) by Delicious Brains
```

**Comment by xvigoa** [comment] 2018-01-08 18:53
Hello,

I have the same problem in frontend, chek the video: https://youtu.be/ILPI3KU_B8Y

**Comment by ianmjones** [comment] 2018-01-09 10:42
@xvigoa You seem to be using some sort of page builder, which one?

**Comment by sankalpsans** [comment] 2018-01-22 13:01
@xvigoa This solves the problem well, but defeats the overall purpose of this major update, i.e. making the content stored in WP agnostic to where the images are actually being served from.

Nevertheless, this will work, but you will need to keep commenting those lines out (and maybe some more lines) after each time you update the plugin.

**Comment by fabiolrs** [comment] 2018-01-30 13:09
@ianmjones Although it's helpful for debugging purposes to know which page builder she is using, I can confirm that using multiple page builders have no overall impact in this bug.

I've used multiple themes while testing, from Divi (the one she is using) to others that included Visual Composer and of course no page builder at all, all produce the same problem.

The error lies with lines 17, 18, 19 of as3cf-s3-to-local.php, that filters content before saving it to the database and content being filtered incorrectly.

**Comment by fabiolrs** [comment] 2018-01-30 13:13
@ianmjones I would suggest changing the filter to get all img/src tags on the page and assigning it to an array. Maybe use DomDocument() or something, so you can easily get tags by using getElementsByTagName.

That way you can better get src values and change them individually.

I am more than glad to help.

**Comment by ianmjones** [comment] 2019-04-29 11:08
WP Offload Media Lite 2.1.1 has been released with support for the WordPress MU Domain Mapping plugin and other bug fixes for filtering content.

**Closed by ianmjones** 2019-04-29 11:08 UTC
Labels: pending dev
