### ISSUE TITLE
Error fetching buckets — Internal Server Error

### ISSUE THREAD

**Issue by altimea** [deliciousbrains/wp-amazon-s3-and-cloudfront#265] opened 2015-08-12 01:55 UTC

**Comment by polevaultweb** [comment] 2015-08-12 06:05
@altimea Can you try editing your wp-config.php file to replace this line -

`define( 'WP_DEBUG', false );`

With these lines -

```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false); 
```

This means that any errors are logged to `/wp-content/debug.log', because some errors are not visible on screen. Can you then try the process again and then post the debug.log?

More details about that at http://codex.wordpress.org/Editing_wp-config.php#Debug

**Comment by MattyLB** [comment] 2015-08-13 14:28
I've added these lines on my EasyEngine created site and it's not logging
anything. One thing about easyengine is that it moves the wp-config.php
file to a secure location outside of the served folders, so this may have
something to do with it not logging debug information.

I'll send admin credentials asap so you can look into this from the WP
back-end, but I doubt there is much you can do from my installation as my
EC2 instance is locked down by default and allows zero FTP access without a
key and many hurdles to jump through to allow access to anyone other than
myself. That said, if you have access to AWS and a free-tier EC2, you can
see what myself and others using EE from rtcamp.com (with NGiNX enabled)
are going through from your own environment.

Thanks,
Matt

**Comment by A5hleyRich** [comment] 2015-11-25 09:46
No further reports. Closing issue.

**Comment by AndrewNMathews** [comment] 2016-10-22 03:57
Hello,

I am having this issue also.

**Comment by andrienpecson** [comment] 2017-12-28 03:46
+1 on the issue

**Comment by A5hleyRich** [comment] 2017-12-28 08:34
@andrienpecson  Can you try editing your wp-config.php file to replace this line -

```
define( 'WP_DEBUG', false );
```

With these lines -

```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false); 
```

This means that any errors are logged to `/wp-content/debug.log', because some errors are not visible on screen. Can you then try the process again and then post the debug.log?

More details about that at http://codex.wordpress.org/Editing_wp-config.php#Debug

**Comment by ianmjones** [comment] 2018-02-09 11:11
No more info provided and not reproducible, closing.

**Closed by ianmjones** 2018-02-09 11:11 UTC
Labels: awaiting response
