### ISSUE TITLE
Upgrade to AWS SDK v3 planned?

### ISSUE THREAD

**Issue by benbowler** [deliciousbrains/wp-amazon-s3-and-cloudfront#374] opened 2017-04-26 13:28 UTC
Good afternoon. I've been chatting with Ashley over email about the pro version of the addon. It's conflicting with a plugin that I've developed because I'm using the AWS SDK v3 and this plugin uses v2. Are you considering upgrading WP Offload S3 to use the v3 SDK?

If not would you accept a PR with the upgrade?

Best.

Ben

**Comment by A5hleyRich** [comment] 2017-04-26 13:33
Hi Ben,

It's something we're looking into, but upgrading isn't an option at the moment due to the bumped PHP requirement. We wrote more about it here: https://deliciousbrains.com/wp-offload-s3-1-4-released/#sdk

**Comment by benbowler** [comment] 2017-04-26 13:40
Great thank Ashley. I'll have a think.

**Comment by aaemnnosttv** [comment] 2017-06-27 20:23
Closing as duplicate of #267

**Closed by aaemnnosttv** 2017-06-27 20:23 UTC
