### ISSUE TITLE
Resizing the image using WordPress image editor not upload the image to S3

### ISSUE THREAD

**Issue by danieluyo** [deliciousbrains/wp-amazon-s3-and-cloudfront#388] opened 2017-07-03 14:53 UTC
* Remove Files From Server - ON
* Copy Files to S3 - ON 
* Rewrite File URLs - ON
![captura de pantalla 2017-07-03 a las 9 49 58](https://user-images.githubusercontent.com/17558554/27798043-7087506c-5fd5-11e7-9a79-e64abd640127.png)

**Comment by aaemnnosttv** [comment] 2017-07-03 16:16
Hi there! You'll need to provide a bit more detail as to how to reproduce this as I am unable to do so using a clean install with the options specified.

Here are my settings:
```json
{
   "copy-to-s3" : "1",
   "force-https" : "0",
   "remove-local-file" : "1",
   "use-yearmonth-folders" : "1",
   "object-versioning" : "1",
   "enable-object-prefix" : "1",
   "region" : "eu-central-1",
   "cloudfront" : "",
   "object-prefix" : "lite388.dev/uploads/",
   "serve-from-s3" : "1",
   "post_meta_version" : 6,
   "domain" : "path"
}
```

I had no problem editing an image that I added which was removed from the server and uploaded to S3 as well as can be seen by the e1499.. in the filename.

![image](https://user-images.githubusercontent.com/1621608/27800799-9231f94e-6023-11e7-910f-a3d8bd71e620.png)

The SyntaxError you have in your console is likely the cause of the problem you're seeing. You should find out what is causing that first. If you see Offload S3 is implicated in the error's trace, please include that for us to see. We've seen this kind of thing caused by leading/trailing whitespace in theme/plugin files before the opening `<?php` or after the closing `?>`

**Comment by Chinese1904** [comment] 2017-07-26 03:45
I have / had the same issue and posted about it here https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/358#issuecomment-312603908

You should try disabling "Remove Files From Server" and I bet you it will work.

**Comment by ianmjones** [comment] 2018-02-09 11:33
No further info provided, not able to reproduce, closing.

**Closed by ianmjones** 2018-02-09 11:33 UTC
Labels: unconfirmed
