### ISSUE TITLE
Error adding an image on the user panel wordpress

### ISSUE THREAD

**Issue by brasilmorar** [deliciousbrains/wp-amazon-s3-and-cloudfront#305] opened 2016-02-04 19:53 UTC
Dear,

Installed a new setup in my wordpress site using the plugin WP Offload S3, I never had problems it is configured to download the images in bucket s3, set up to keep everything in s3 and delete the server. I am now with this configuration:

WordPress: 4.4.2
Web Server: nginx/1.8.1
PHP: 5.6.17-3+deb.sury.org~trusty+1
MySQL: 10.0.17-MariaDB-log
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 128M
Blocked External HTTP Requests: None
WP Locale: pt_BR
Debug Mode: No
WP Max Upload Size: 100 MB
PHP Time Limit: 300
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.2e 3 Dec 2015
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.1.1-dev
Imagick: Enabled

Media Files: 204
Media Files on S3: 204
Number of Image Sizes: 5

Bucket: aws-mybucket
Region: sa-east-1
Copy Files to S3: On
Rewrite File URLs: On

URL Preview: https://cdn.mysite.com/midia/2016/02/04174323/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: midia
Use Year/Month: On
SSL: https
Remove Files From Server: On
Object Versioning: On
Far Future Expiration Header: On
Copy HiDPI (@2x) Images: On

Active Plugins:
404 to 301 (v2.1.4) by Joel James
Amazon Web Services (v0.3.4) by Delicious Brains
Easy WP SMTP (v1.2.2) by wpecommerce
Google Authenticator (v0.47) by Henrik Schack
Importador do WordPress (v0.6.1) by wordpressdotorg
Maintenance (v2.6) by fruitfulcode
Nginx Helper (v1.9.6) by rtCamp
Reales WP STPT (v1.0.5) by Marius Nastase
Redis Object Cache (v1.2.1) by Till Krüss
Rename wp-login.php (v2.5.5) by Ella Iseulde Van Dorpe
WP Offload S3 (v0.9.12) by Delicious Brains
Wordfence Security (v6.0.24) by Wordfence
Yoast SEO (v3.0.7) by Equipe da Yoast

I am facing the following problem:

When I walk into a user panel of my site and add a picture she carries with error and will not appear, only see the word: thumb. If I click on the picture of the way I see it:

https://www.mysite.com/wp-content/uploads/2016/02/image.jpg and put the URL in the browser see the 404 Not Found nginx. When I walk in my wordpress control panel and access the media library see the image as normal with the right one: https://cdn.mysite.com/midia/2016/02/04174323/photo.jpg.

In the plugin settings define the file as media and everything is right. What could be happening?

Thank you,

Carlos

**Comment by aaemnnosttv** [comment] 2017-06-27 15:53
Closing as unable to reproduce. If this is still an issue for you please re-open.

**Closed by aaemnnosttv** 2017-06-27 15:53 UTC
