### ISSUE TITLE
How to handle non media library images to AWS s3?

### ISSUE THREAD

**Issue by worldweb** [deliciousbrains/wp-amazon-s3-and-cloudfront#588] opened 2021-08-25 11:17 UTC
I am using the Geodirectory plugin with Offload Media plugin
Here is the link to Geodirectory plugin - https://wordpress.org/plugins/geodirectory/

Geodirectory allows uploading multiple images for post featured images. - http://prntscr.com/1qht47q
It only uploads the first image to the media library and other doesn't exist as a media library. It exists in the upload folder and geodirectory handle using own table. 

Is there anyway to handle non-media library images to Aws s3?

**Comment by ianmjones** [comment] 2021-11-29 15:54
If that Geodirectory plugin creates a Media Library item that the other files you mention are associated with, then you can use the `as3cf_attachment_file_paths` filter to tell WP Offload Media about the extra files.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/beb2e0f1bba71be7b462a60209e5ff630a57437e/amazon-s3-and-cloudfront-tweaks.php#L708

Otherwise, I'm closing this issue as a duplicate of https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/7.

**Closed by ianmjones** 2021-11-29 15:54 UTC
Labels: duplicate, feature request
