### ISSUE TITLE
Disable "define( 'DBI_AWS_ACCESS_KEY_ID', getenv('DBI_AWS_ACCESS_KEY_ID') );" in wp-config.php

### ISSUE THREAD

**Issue by soyanakagawa** [deliciousbrains/wp-amazon-s3-and-cloudfront#404] opened 2017-10-17 02:00 UTC
I wanted to use Environment Variables in wp-config.php. Because it's more secure.
I set  "define( 'DBI_AWS_ACCESS_KEY_ID', getenv('DBI_AWS_ACCESS_KEY_ID' );" in wp-config.php, and Environment Variables DBI_AWS_ACCESS_KEY_ID in host server.
Then the plugin "Amazon Web Service" was enable.
But S3 Offload had a error. 
So I wrote variables direct. Then  S3 Offload be enable!

Is it bug? I think we should use getenv().

Thanks

**Comment by aaemnnosttv** [comment] 2017-10-17 07:28
It looks like you are just missing a closing parenthesis for the constant definition.

Try this:
```php
define( 'DBI_AWS_ACCESS_KEY_ID', getenv( 'DBI_AWS_ACCESS_KEY_ID' ) );
```

**Comment by soyanakagawa** [comment] 2017-10-23 10:04
Oh, sorry. Typo.
I fixed it but result is same.

**Comment by aaemnnosttv** [comment] 2017-10-23 16:32
What exactly is the error you're seeing?

**Comment by soyanakagawa** [comment] 2017-10-25 05:37
" You must first set your AWS access keys to use this addon. "
![2017-10-25 14 35 43](https://user-images.githubusercontent.com/7406214/31982095-db5afb8a-b991-11e7-82cd-f71a2e18ba51.png)

and AWS ↓
![2017-10-25 14 36 00](https://user-images.githubusercontent.com/7406214/31982119-f53e3b52-b991-11e7-8b4a-e946c1b21d65.png)

**Comment by aaemnnosttv** [comment] 2017-11-08 05:50
Can you confirm that both `DBI_AWS_ACCESS_KEY_ID` and `DBI_AWS_SECRET_ACCESS_KEY` constants are being defined?

It sounds like you might have an issue with the environment variables being set. If you're referencing environment variables that are returning empty values, the constants would still be defined (resulting in the message on the AWS plugin that they are) but Offload S3 thinks they are not because the access key and secret are blank/empty.

Try something like this to test if your environment variables are being set correctly:

```php
// in your wp-config.php
var_dump(
    getenv( 'DBI_AWS_ACCESS_KEY_ID' ),
    getenv( 'DBI_AWS_SECRET_ACCESS_KEY' )
);
die;
```

This will take your site down as long as that code is there of course, so just be mindful of when you want to test that.

**Comment by aaemnnosttv** [comment] 2017-11-20 07:15
Closing this out as I have confirmed that these constants work when set from environment variables and not a bug. As to your issue, as I mentioned above, the problem is likely that your environment variables are not getting set. If you continue to experience problems, you might reach out to the community through the [plugin's forum](https://wordpress.org/support/plugin/amazon-s3-and-cloudfront).

**Closed by aaemnnosttv** 2017-11-20 07:15 UTC
