### ISSUE TITLE
S3 files replacing for www.[mydomain], but not the root domain...

### ISSUE THREAD

**Issue by jgalicinski** [deliciousbrains/wp-amazon-s3-and-cloudfront#378] opened 2017-06-06 21:19 UTC
if you go to www.reachingtheheartofzambia.org, you will see images.  If you go to: reachingtheheartofzambia.org, you will not.  This is because all the images were uploaded with www.reachingtheheartofzambia.org..  Please fix.

[www.reachingtheheartofzambia.org-diagnostic-log-20170606211623.txt](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/files/1056390/www.reachingtheheartofzambia.org-diagnostic-log-20170606211623.txt)

**Comment by aaemnnosttv** [comment] 2017-06-07 08:07
I'm not sure I understand. Are you trying to change the domain to not use the `www` subdomain?

**Comment by ianmjones** [comment] 2017-06-07 10:39
@jgalicinski WP Offload S3 will only filter what it recognizes as "local" URLs.

If your site uses more than one domain, then you need to have properly working domain mapping set up so that any plugin can recognize the extra domains as being for the current site.

It looks like you've got around the problem since raising the issue by redirecting to the proper www site. May we close this issue?

**Comment by aaemnnosttv** [comment] 2017-06-28 10:06
Looks like the issue is resolved for you now. As Ian said, the local URLs in your content need to use the same domain as your site's home URL. `www` and non-www are different domains, which is why the content filtering was not working for you.

Feel free to reopen this if you believe there is a bug for us to investigate.

**Closed by aaemnnosttv** 2017-06-28 10:06 UTC
