### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by andymilk** [deliciousbrains/wp-amazon-s3-and-cloudfront#371] opened 2017-03-27 23:45 UTC
Hi guys,

I'm having multiple issues.

1.  I tried manually uploaded all of our Media Library files to S3 and then doing a database search & replace, but the files are still being loaded from the local library.

2.  I tried Regenerate Thumbnails but the files are still being loaded (source files for regenerating AND destination files after regenerating) from local.

Here's my info:
site_url(): https://preview.rentpatina.ascenderstudios.com
home_url(): https://preview.rentpatina.ascenderstudios.com
Database Name: rentpatina
Table Prefix: wp_
WordPress: 4.7.3
Web Server: Apache
PHP: 5.6.30-0+deb8u1
MySQL: 5.5.5
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 40M
Memory Usage: 12 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 2 MB
PHP Time Limit: 30
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1t  3 May 2016
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.1.1-dev
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 13,776
Media Files on S3: 1
Number of Image Sizes: 6

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (600x600)
large (1024x1024)
hero1 (1180x369)
instagram (640x640)

WP_CONTENT_DIR: /var/www/vhosts/rentpatina.com/httpdocs/wp-content
WP_CONTENT_URL: https://preview.rentpatina.ascenderstudios.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/vhosts/rentpatina.com/httpdocs/wp-content/plugins
WP_PLUGIN_URL: https://preview.rentpatina.ascenderstudios.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: rentpatina
Region: 
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
https://preview.rentpatina.ascenderstudios.com/wp‑content/uploads/2017/03/photo.jpg
S3 URL:
https://s3.amazonaws.com/rentpatina/wp‑content/uploads/2017/03/27194356/photo.jpg

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: Off
Remove Files From Server: On
Object Versioning: On

Active Theme Name: Patina
Active Theme Folder: patina

Active Plugins:
Admin Columns (v2.5.6.3) by AdminColumns.com
Admin Menu Editor Pro (v1.97) by Janis Elsts
Advanced Custom Fields Character Limiter (v0.1) by daltonrooney
Advanced Custom Fields Pro (v5.3.2.2) by elliot condon
Ajax Search Pro (v4.9.7) by Ernest Marcinko
Akismet (v3.2) by Automattic
Amazon Web Services (v1.0.2) by Delicious Brains
Better Related Content (v0.4.3.4) by Nicolas Kuttler
Crazyegg-Heatmap-Tracking (v1.1) by Crazyegg
Custom Post Type UI (v1.4.1) by WebDevStudios
Disable Comments (v1.5.2) by Samir Shah
DsgnWrks Instagram Importer (v1.3.9) by DsgnWrks
Easy Video Player (v1.1.4) by naa986
Gravity Forms (v2.0.7) by rocketgenius
Gravity Forms MailChimp Add-On (v3.7.1) by rocketgenius
Imsanity (v2.3.6) by Jason Hinkle
Instagram-Widget-for-WordPress (v1.3.1) by David Register
Members (v1.1.2) by Justin Tadlock
Patina Wishlist (v1.6.2) by Raygun
Pinterest RSS Widget (v100000) by bkmacdaddy designs
Portfolio Framework (v1.1.1) by Raygun
Posts Viewed Recently (v11.2) by Amit Sonkhiya, Kamal Agrawal
Raygun Custom Admin (v1.0.1) by Raygun Design, LLC
Regenerate Thumbnails (v2.2.6) by Alex Mills (Viper007Bond)
Simple Image Sizes (v3.1.1) by Rahe
Simple Social Icons (v1.0.13) by Nathan Rice
Twitter Widget Pro (v2.8.0) by Aaron D. Campbell
WP GIF Player (v0.8) by David Bedenknecht
WP Offload S3 Lite (v1.1.6) by Delicious Brains
WordPress Editorial Calendar (v3.6.2) by Colin Vernon, Justin Evans, Joachim Kudish, Mary Vogt, and Zack Grossbart
WordPress Importer (v0.6.3) by wordpressdotorg
Yoast SEO (v3.5) by Team Yoast

Thanks,
Andy

**Comment by A5hleyRich** [comment] 2017-03-28 09:25
WP Offload S3 only supports files uploaded via the Media Library. There isn't currently a method for linking up existing files on S3.

**Comment by andymilk** [comment] 2017-03-28 11:34
On this page, it says: "Painlessly Upload Your Existing Media Library"

https://deliciousbrains.com/wp-offload-s3/

**Comment by A5hleyRich** [comment] 2017-03-28 11:37
That's the sales page for the Pro version, which includes a tool to upload your existing Media Library. It doesn't allow you to link up existing files on S3.

**Comment by andymilk** [comment] 2017-03-28 11:40
OK, thanks.  Sorry about that, I misunderstood.

I'm having trouble even getting the basic functionality to work.

It looks like my Media Library uploader is broken and I'm getting mod_security errors.

![error](https://cloud.githubusercontent.com/assets/69801/24403194/c1a60972-1389-11e7-80a9-4256ac276d31.png)

**Comment by aaemnnosttv** [comment] 2017-06-27 20:21
The error shown is a WordPress error likely caused by the configuration of your server. Do you get the same error if Offload S3 is disabled when uploading the same image?

**Comment by aaemnnosttv** [comment] 2017-06-28 12:29
Closing this out for now. Please re-open if you find there may be a bug with the most recent version of Offload S3 (currently v1.2).

**Closed by aaemnnosttv** 2017-06-28 12:29 UTC
Labels: unconfirmed
