### ISSUE TITLE
2.3 Uploading documents breaks Media Library

### ISSUE THREAD

**Issue by krasu** [deliciousbrains/wp-amazon-s3-and-cloudfront#515] opened 2019-11-14 15:56 UTC
During non image file upload (`.docx` or `.pdf` for example) [`Media_Library_Item`](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/2.3/classes/items/media-library-item.php) object is stored as attachment meta data in metadata table. Which leads to inability to view [Media Library](https://wordpress.org/support/article/media-library-screen/), because of following error:

```
PHP Fatal error:  Uncaught Error: Cannot use object of type DeliciousBrains\\WP_Offload_Media\\Items\\Media_Library_Item as array in ./wp-includes/media.php:3433
Stack trace:
#0 [internal function]: wp_prepare_attachment_for_js(Object(WP_Post))
#1 ./wp-admin/includes/ajax-actions.php(2965): array_map('wp_prepare_atta...', Array)
#2 ./wp-includes/class-wp-hook.php(288): wp_ajax_query_attachments('')
#3 ./wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#4 ./wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 ./wp-admin/admin-ajax.php(175): do_action('wp_ajax_query-a...')
#6 {main}
  thrown in ./wp-includes/media.php on line 3433
```
It happens because [WP expects no data or array](https://codex.wordpress.org/Function_Reference/wp_get_attachment_metadata#Examples) as attachment metadata. 

Issue introduced in version 2.3:
https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/93cd39b38d823e437f8a2ab76274c4980564e7f2/classes/amazon-s3-and-cloudfront.php#L1454-L1459

And could be solved by reverting to returning and storing `$provider_object` array by default:

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/6371429abc63935fe18b0c60f0abb85f7cb06056/classes/amazon-s3-and-cloudfront.php#L1172-L1178

Or by not returning and storing any value by default.

Tested both on WP 5.2.4 and 5.3.

**Comment by ianmjones** [comment] 2019-11-15 13:38
Hmm, can't reproduce.

We thoroughly tested WP Offload Media 2.3 with non-images before release, including zip, pdf, audio and movie files etc.

The way `upload_attachment()` handles the return of metadata has not changed for WP Offload Media 2.3, it still returns the input `$data` as long as it is not `null`, otherwise it returns our own data for use by the (internal to OME) calling function.

If the `wp_update_attachment_metadata` function or similarly named triggered filter supply non-null data (as is the norm for WordPress Core calls) to the function, then `upload_attachment()` is going to return it.

The only way I can see this mechanism going astray is if something meddles with the data and accidentally sets it to `null`.

Please confirm you weren't using the Smush plugin while running your tests, just so we can rule that out.

Any other information you can supply to help me reproduce the problem?

**Comment by krasu** [comment] 2019-11-15 15:40
> The only way I can see this mechanism going astray is if something meddles with the data and accidentally sets it to `null`.

Yes, that is exactly what happens in our case and only for non image files. 

I've checked with fresh test setup and it seems like problem is indeed caused by Smush, it wipes metadata for non image files, which leads to `\Amazon_S3_And_CloudFront::wp_update_attachment_metadata` having `null` as `$data`.

I've checked and I see what `\Amazon_S3_And_CloudFront::upload_attachment` is only used inside `\Amazon_S3_And_CloudFront::wp_update_attachment_metadata`, could you please make `\Amazon_S3_And_CloudFront::wp_update_attachment_metadata` to return `null` instead of `$as3cf_item`? It would be nice solution to make plugin compatible with Smush.

**Comment by ianmjones** [comment] 2019-11-19 13:09
WP Offload Media Lite 2.3.1 has been released with code to help protect against this kind of thing happening again.

Smush have also released a new version of there plugin that hopefully fixes compatibility with WP Offload Media.

**Closed by ianmjones** 2019-11-19 13:09 UTC
